import { randomUUID } from "node:crypto";
import { desc, eq, getTableColumns } from "drizzle-orm";
import { db } from "../db.js";
import { opportunities } from "../schema/opportunity.js";
import { projects } from "../schema/project.js";
import { researchPackages } from "../schema/research-package.js";
import { projectSelectionPolicies, topicSelections } from "../schema/topic-selection.js";

const selectionColumns = getTableColumns(topicSelections);
export type TopicSelectionWithOpportunity = typeof topicSelections.$inferSelect & { projectName: string; opportunityTitle: string; opportunityScore: number; representativeUrl: string; researchPackageConfidenceScore: number | null; researchPackageSourceCount: number | null; researchPackageStatus: string | null; };
export const defaultProjectSelectionPolicy = { minimumOpportunityScore: 60, minimumResearchConfidence: 60, minimumIndependentSources: 2, maxSelectedPerRun: 3, requireResearchPackage: true, allowSingleSourceBreakingStories: false };

export class TopicSelectionRepository {
  async findPolicy(projectId: string) { const rows = await db.select().from(projectSelectionPolicies).where(eq(projectSelectionPolicies.projectId, projectId)); return rows[0]; }
  async upsertPolicy(projectId: string, data: typeof defaultProjectSelectionPolicy) { const existing = await this.findPolicy(projectId); const now = new Date().toISOString(); if (existing) { await db.update(projectSelectionPolicies).set({ ...data, updatedAt: now }).where(eq(projectSelectionPolicies.projectId, projectId)); return (await this.findPolicy(projectId))!; } await db.insert(projectSelectionPolicies).values({ projectId, ...data, createdAt: now, updatedAt: now }); return (await this.findPolicy(projectId))!; }
  async findAll(projectId?: string): Promise<TopicSelectionWithOpportunity[]> { const query = db.select({ ...selectionColumns, projectName: projects.name, opportunityTitle: opportunities.title, opportunityScore: opportunities.score, representativeUrl: opportunities.representativeUrl, researchPackageConfidenceScore: researchPackages.confidenceScore, researchPackageSourceCount: researchPackages.sourceCount, researchPackageStatus: researchPackages.status }).from(topicSelections).innerJoin(projects, eq(topicSelections.projectId, projects.id)).innerJoin(opportunities, eq(topicSelections.opportunityId, opportunities.id)).leftJoin(researchPackages, eq(topicSelections.researchPackageId, researchPackages.id)); return projectId ? query.where(eq(topicSelections.projectId, projectId)).orderBy(desc(topicSelections.evaluatedAt)) : query.orderBy(desc(topicSelections.evaluatedAt)); }
  async findById(id: string): Promise<TopicSelectionWithOpportunity | undefined> { const rows = await db.select({ ...selectionColumns, projectName: projects.name, opportunityTitle: opportunities.title, opportunityScore: opportunities.score, representativeUrl: opportunities.representativeUrl, researchPackageConfidenceScore: researchPackages.confidenceScore, researchPackageSourceCount: researchPackages.sourceCount, researchPackageStatus: researchPackages.status }).from(topicSelections).innerJoin(projects, eq(topicSelections.projectId, projects.id)).innerJoin(opportunities, eq(topicSelections.opportunityId, opportunities.id)).leftJoin(researchPackages, eq(topicSelections.researchPackageId, researchPackages.id)).where(eq(topicSelections.id, id)); return rows[0]; }
  async upsert(data: Omit<typeof topicSelections.$inferInsert, "id" | "createdAt" | "updatedAt">): Promise<TopicSelectionWithOpportunity> { const existing = (await this.findAll(data.projectId)).find((selection) => selection.opportunityId === data.opportunityId); const now = new Date().toISOString(); if (existing) { await db.update(topicSelections).set({ ...data, updatedAt: now }).where(eq(topicSelections.id, existing.id)); return (await this.findById(existing.id))!; } const id = randomUUID(); await db.insert(topicSelections).values({ id, createdAt: now, updatedAt: now, ...data }); return (await this.findById(id))!; }
}
