import { randomUUID } from 'node:crypto';
import { and, eq, isNull, lte } from 'drizzle-orm';
import { db } from '../db.js';
import { videoCompositionPlans, videoCompositionPreparationClaims, videoCompositionScenes } from '../schema/video-composition.js';
type PlanWrite=Omit<typeof videoCompositionPlans.$inferInsert,'id'|'createdAt'|'updatedAt'>;
type SceneWrite=Omit<typeof videoCompositionScenes.$inferInsert,'id'|'compositionPlanId'|'sceneIndex'|'createdAt'>;
export class VideoCompositionRepository {
 static readonly PREPARATION_CLAIM_TIMEOUT_MS=5*60*1000;
 async acquirePreparationClaim(contentScriptId:string){const claimToken=randomUUID();const claimedAt=new Date().toISOString();const staleBefore=new Date(Date.now()-VideoCompositionRepository.PREPARATION_CLAIM_TIMEOUT_MS).toISOString();return db.transaction(tx=>{const takeover=tx.update(videoCompositionPreparationClaims).set({claimToken,claimedAt}).where(and(eq(videoCompositionPreparationClaims.contentScriptId,contentScriptId),lte(videoCompositionPreparationClaims.claimedAt,staleBefore))).run();if(takeover.changes===1)return claimToken;const inserted=tx.insert(videoCompositionPreparationClaims).values({contentScriptId,claimToken,claimedAt}).onConflictDoNothing().run();return inserted.changes===1?claimToken:undefined;});}
 async releasePreparationClaim(contentScriptId:string,claimToken:string){db.delete(videoCompositionPreparationClaims).where(and(eq(videoCompositionPreparationClaims.contentScriptId,contentScriptId),eq(videoCompositionPreparationClaims.claimToken,claimToken))).run();}
 async findByContentScriptId(contentScriptId:string){const plan=(await db.select().from(videoCompositionPlans).where(eq(videoCompositionPlans.contentScriptId,contentScriptId)))[0];if(!plan)return undefined;const scenes=await db.select().from(videoCompositionScenes).where(eq(videoCompositionScenes.compositionPlanId,plan.id)).orderBy(videoCompositionScenes.sceneIndex);return {...plan,scenes};}
 async findSceneById(sceneId:string){return db.select().from(videoCompositionScenes).where(eq(videoCompositionScenes.id,sceneId)).get();}
 async bindMediaAsset(sceneId:string,candidateId:string,candidateIdentityHash:string,mediaAssetId:string){const result=db.update(videoCompositionScenes).set({mediaAssetId}).where(and(eq(videoCompositionScenes.id,sceneId),eq(videoCompositionScenes.selectedCandidateId,candidateId),eq(videoCompositionScenes.candidateIdentityHash,candidateIdentityHash),isNull(videoCompositionScenes.mediaAssetId))).run();return result.changes===1;}
 async upsert(data:PlanWrite,scenes:SceneWrite[]){const timestamp=new Date().toISOString();db.transaction(tx=>{tx.insert(videoCompositionPlans).values({id:randomUUID(),createdAt:timestamp,updatedAt:timestamp,...data}).onConflictDoUpdate({target:videoCompositionPlans.contentScriptId,set:{...data,updatedAt:timestamp}}).run();const plan=tx.select().from(videoCompositionPlans).where(eq(videoCompositionPlans.contentScriptId,data.contentScriptId)).get();if(!plan)throw new Error('Unable to persist video composition plan');tx.delete(videoCompositionScenes).where(eq(videoCompositionScenes.compositionPlanId,plan.id)).run();if(scenes.length)tx.insert(videoCompositionScenes).values(scenes.map((scene,sceneIndex)=>({id:randomUUID(),compositionPlanId:plan.id,sceneIndex,createdAt:timestamp,...scene}))).run();});const stored=await this.findByContentScriptId(data.contentScriptId);if(!stored)throw new Error('Unable to read video composition plan');return stored;}
}
