import "dotenv/config";
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: [
    "./src/schema/project.ts",
    "./src/schema/project-editorial-profile.ts",
    "./src/schema/content.ts",
    "./src/schema/content-script.ts",
    "./src/schema/content-style-profile.ts",
    "./src/schema/scene-plan.ts",
    "./src/schema/audio-generation.ts",
    "./src/schema/visual-asset.ts",
    "./src/schema/visual-asset-acquisition.ts",
    "./src/schema/video-composition.ts",
    "./src/schema/video-motion.ts",
    "./src/schema/video-render.ts",
    "./src/schema/media-asset.ts",
    "./src/schema/research-source.ts",
    "./src/schema/signal.ts",
    "./src/schema/opportunity.ts",
    "./src/schema/opportunity-metrics.ts",
    "./src/schema/editorial-assessment.ts",
    "./src/schema/ai-execution.ts",
    "./src/schema/ai-batch.ts",
    "./src/schema/research-package.ts",
    "./src/schema/topic-selection.ts",
    "./src/schema/topic-candidate.ts",
    "./src/schema/semantic-embedding-cache.ts",
    "./src/schema/research-expansion.ts",
    "./src/schema/production-queue.ts",
    "./src/schema/job.ts",
    "./src/schema/workflow.ts",
    "./src/schema/agent-runtime.ts",
    "./src/schema/agent-pipeline.ts",
  ],
  out: "./migrations",
  dialect: "sqlite",
  dbCredentials: {
    url: process.env.DATABASE_URL || "content-os.db",
  },
});
