import { integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const geographicReferences = sqliteTable('geographic_references', {
  id: text('id').primaryKey(), canonicalName: text('canonical_name').notNull(), aliases: text('aliases_json', { mode: 'json' }).$type<string[]>().notNull(), entityType: text('entity_type').notNull(), point: text('point_json', { mode: 'json' }).$type<{ latitude: number; longitude: number } | null>(), bounds: text('bounds_json', { mode: 'json' }).$type<{ west: number; south: number; east: number; north: number } | null>(), geometryReference: text('geometry_reference'), parentReferenceId: text('parent_reference_id'), provenanceSourceId: text('provenance_source_id').notNull(), provenanceReference: text('provenance_reference').notNull(), confidence: integer('confidence').notNull(), reviewStatus: text('review_status').notNull(), version: text('version').notNull(), revision: integer('revision').notNull(), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(),
}, (table) => [uniqueIndex('geographic_references_canonical_version_unique').on(table.canonicalName, table.version)]);

export const geographicRelationships = sqliteTable('geographic_relationships', {
  id: text('id').primaryKey(), fromReferenceId: text('from_reference_id').notNull(), toReferenceId: text('to_reference_id').notNull(), relationshipType: text('relationship_type').notNull(), geometryReference: text('geometry_reference'), provenanceSourceId: text('provenance_source_id').notNull(), provenanceReference: text('provenance_reference').notNull(), reviewStatus: text('review_status').notNull(), version: text('version').notNull(), revision: integer('revision').notNull(), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(),
}, (table) => [uniqueIndex('geographic_relationships_identity_unique').on(table.fromReferenceId, table.toReferenceId, table.relationshipType, table.version)]);
