import { integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

type StoredVisualAssetAcquisitionProviderPlan = { id: string; enabled: boolean; priority: number; capabilities: string[]; strategies: string[]; resultLimit: number; version: string; configurationIdentity: string };

export const visualAssetAcquisitionRuns = sqliteTable('visual_asset_acquisition_runs', {
  id: text('id').primaryKey(), projectId: text('project_id').notNull(), contentScriptId: text('content_script_id').notNull(), manifestId: text('manifest_id').notNull(), manifestInputHash: text('manifest_input_hash').notNull(), version: text('version').notNull(), inputHash: text('input_hash').notNull(), status: text('status').notNull(), requestedRequirementIds: text('requested_requirement_ids', { mode: 'json' }).$type<string[]>().notNull(), providerPlan: text('provider_plan', { mode: 'json' }).$type<StoredVisualAssetAcquisitionProviderPlan[]>().notNull(), preparedQueryCount: integer('prepared_query_count').notNull(), providerRequestCount: integer('provider_request_count').notNull(), candidatesDiscovered: integer('candidates_discovered').notNull(), candidatesAccepted: integer('candidates_accepted').notNull(), candidatesRejected: integer('candidates_rejected').notNull(), failureCode: text('failure_code'), startedAt: text('started_at'), completedAt: text('completed_at'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull(),
}, (table) => [uniqueIndex('visual_asset_acquisition_runs_manifest_input_unique').on(table.manifestId, table.inputHash)]);
export const visualAssetAcquisitionPlans = sqliteTable('visual_asset_acquisition_plans', {
  id: text('id').primaryKey(), runId: text('run_id').notNull(), planIndex: integer('plan_index').notNull(), requirementId: text('requirement_id').notNull(), plannedSceneId: text('planned_scene_id').notNull(), requirementType: text('requirement_type').notNull(), acquisitionStrategy: text('acquisition_strategy').notNull(), capability: text('capability'), providerIds: text('provider_ids', { mode: 'json' }).$type<string[]>().notNull(), queries: text('queries', { mode: 'json' }).$type<string[]>().notNull(), expectedMediaType: text('expected_media_type').notNull(), targetAspectRatio: text('target_aspect_ratio').notNull(), preferredOrientation: text('preferred_orientation').notNull(), licenceRequirements: text('licence_requirements', { mode: 'json' }).$type<{ commercialUseRequired: boolean; modificationAllowed: boolean; attributionRequired: boolean; provenanceRequired: boolean; unknownLicenceRequiresManualReview: boolean }>().notNull(), resultLimit: integer('result_limit').notNull(), automaticAcquisitionAllowed: integer('automatic_acquisition_allowed', { mode: 'boolean' }).notNull(), skipReason: text('skip_reason'), manualReviewReasons: text('manual_review_reasons', { mode: 'json' }).$type<string[]>().notNull(), createdAt: text('created_at').notNull(),
}, (table) => [uniqueIndex('visual_asset_acquisition_plans_run_index_unique').on(table.runId, table.planIndex)]);
