/**
 * Runtime source for the renderer's isolated Remotion bundle.  It deliberately
 * has no application imports: every visual is reconstructed solely from the
 * immutable internalVisual snapshot carried by the render input.
 */
export const remotionInternalVisualRuntimeSource = String.raw`
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const projectPoint=({latitude,longitude})=>({x:clamp((longitude+180)/360*100,2,98),y:clamp((90-latitude)/180*100,2,98)});
const internalProgress=(frame,duration)=>interpolate(frame,[0,Math.max(1,duration-1)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const entrance=(frame,delay=0)=>interpolate(frame,[delay,delay+12],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const InternalLabels=({labels,frame})=><div style={{position:'absolute',left:68,right:68,bottom:126,display:'flex',flexWrap:'wrap',gap:12,justifyContent:'center'}}>{(labels||[]).map((label,index)=>{const visible=entrance(frame,index*4);return <div key={index} style={{opacity:visible,transform:'translateY('+(1-visible)*16+'px)',padding:'9px 14px',borderRadius:999,background:'#07111fd9',border:'1px solid #8fc6e6',color:'#effaff',fontFamily:'Arial,sans-serif',fontSize:25,fontWeight:700}}>{label}</div>})}</div>;
const MapScene=({visual,duration})=>{const frame=useCurrentFrame(),spec=visual.spec,progress=internalProgress(frame,duration),push=1+progress*.06;return <AbsoluteFill style={{overflow:'hidden',background:'radial-gradient(circle at 55% 38%,#205d85 0,#102d4b 38%,#071526 78%)'}}><AbsoluteFill style={{transform:'scale('+push+')'}}><svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid slice" width="100%" height="100%" aria-label={spec.focus}><rect width="100" height="100" fill="#102f4c"/><path d="M0 15H100M0 30H100M0 45H100M0 60H100M0 75H100M0 90H100M10 0V100M25 0V100M40 0V100M55 0V100M70 0V100M85 0V100" stroke="#5ca1c2" strokeOpacity=".28" strokeWidth=".18"/>{(spec.highlightedRegions||[]).map((region,index)=>{const x=14+(index%3)*25,y=28+Math.floor(index/3)*18;return <g key={region}><rect x={x} y={y} width="20" height="13" rx="2" fill="#f2ba4d" fillOpacity=".34" stroke="#ffd77e" strokeWidth=".4"/><text x={x+10} y={y+7.8} textAnchor="middle" fontSize="3.2" fill="#fff4d5">{region}</text></g>})}{(spec.routes||[]).map((route,index)=>{const points=route.points.map(point=>{const p=projectPoint(point);return p.x+','+p.y}).join(' ');return <polyline key={index} points={points} fill="none" stroke={index%2?'#7ce7ff':'#ffd268'} strokeWidth="1.15" strokeLinecap="round" strokeDasharray="140" strokeDashoffset={140*(1-progress)}/>})}{(spec.markers||[]).map((marker,index)=>{const p=projectPoint(marker),pulse=1+Math.sin((frame+index*8)/5)*.28;return <g key={index}><circle cx={p.x} cy={p.y} r={3*pulse} fill="#ff796a" fillOpacity=".22"/><circle cx={p.x} cy={p.y} r="1.55" fill="#ffbd65" stroke="#fff3cf" strokeWidth=".45"/>{marker.label?<text x={p.x+2.4} y={p.y-2} fontSize="3.4" fill="white" style={{fontWeight:700}}>{marker.label}</text>:null}</g>})}</svg></AbsoluteFill><div style={{position:'absolute',top:86,left:68,right:68,color:'#f4fbff',fontFamily:'Arial,sans-serif',fontSize:68,fontWeight:800,lineHeight:1.05,textShadow:'0 5px 18px #06111bcc'}}>{spec.focus}</div><div style={{position:'absolute',top:176,left:70,width:150,height:5,borderRadius:4,background:'#ffd268'}}/><InternalLabels labels={spec.labels} frame={frame}/></AbsoluteFill>};
const defaultLanes=['M8 26 C32 18 57 42 92 28','M8 49 C30 40 59 63 92 49','M8 72 C34 61 59 82 92 70'];
const FlowCorridorScene=({visual,duration})=>{const frame=useCurrentFrame(),spec=visual.spec,progress=internalProgress(frame,duration),lanes=(spec.lanes||[]).length?spec.lanes.map(route=>'M '+route.points.map(point=>{const p=projectPoint(point);return p.x+' '+p.y}).join(' L ')):defaultLanes,reverse=spec.direction==='reverse',bidirectional=spec.direction==='bidirectional';return <AbsoluteFill style={{overflow:'hidden',background:'linear-gradient(145deg,#071827,#163d58 48%,#090f20)'}}><svg viewBox="0 0 100 100" width="100%" height="100%"><defs><linearGradient id="flowGlow" x1="0" x2="1"><stop stopColor="#47d8ff"/><stop offset="1" stopColor="#f8c65c"/></linearGradient></defs><rect width="100" height="100" fill="url(#flowGlow)" opacity=".06"/>{lanes.map((path,index)=><g key={index}><path d={path} fill="none" stroke="#7fc5dd" strokeOpacity=".26" strokeWidth="1.15"/><path d={path} fill="none" stroke="url(#flowGlow)" strokeWidth=".62" strokeDasharray="3 3" strokeDashoffset={(reverse?-1:1)*(frame*1.5+index*11)}/>{[0,1,2].map(entity=>{const phase=(progress*(reverse?-1:1)+entity/3+index*.11)%1;const x=8+phase*84,y=26+index*23+Math.sin(phase*Math.PI)*((index-1)*5);return <circle key={entity} cx={x} cy={y} r="1.3" fill="#fff4c9"/>})}</g>)}{spec.pressureZone?<g><rect x="62" y="10" width="18" height="80" rx="3" fill="#ff5e5e" opacity=".23"/><path d="M65 20V80M71 16V84M77 20V80" stroke="#ff9c82" strokeWidth=".6"/><text x="71" y="14" textAnchor="middle" fill="#ffe4d4" fontSize="3.1">{spec.pressureZone}</text></g>:null}{bidirectional?<path d="M10 88H90" stroke="#c9eaff" strokeWidth=".5" strokeDasharray="2 2"/>:null}</svg><div style={{position:'absolute',top:88,left:68,right:68,color:'#eefaff',fontFamily:'Arial,sans-serif',fontSize:52,fontWeight:800,lineHeight:1.05}}>Flow in motion</div><InternalLabels labels={spec.labels} frame={frame}/></AbsoluteFill>};
const TextCardScene=({visual})=>{const spec=visual.spec,layout=spec.layout,statistic=spec.emphasis==='statistic';const align=layout==='headline'?'left':layout==='split'?'left':'center';return <AbsoluteFill style={{overflow:'hidden',background:'linear-gradient(160deg,#121b36 0%,#172b4d 50%,#0b1022 100%)'}}><div style={{position:'absolute',inset:-180,background:'radial-gradient(circle at 78% 20%,#f2b84d55,transparent 33%),radial-gradient(circle at 18% 76%,#4ac8e855,transparent 31%)'}}/><div style={{position:'absolute',top:112,left:68,right:68,height:8,borderRadius:4,background:'#f2bf59'}}/><div style={{position:'absolute',left:68,right:68,top:layout==='headline'?250:540,textAlign:align,color:'#f8fbff',fontFamily:'Arial,sans-serif'}}><div style={{fontSize:statistic?126:72,lineHeight:.98,fontWeight:900,letterSpacing:statistic?'-3px':'-1px',textShadow:'0 6px 20px #03091488'}}>{spec.primaryText}</div>{spec.secondaryText?<div style={{marginTop:40,fontSize:38,lineHeight:1.2,fontWeight:600,color:'#c9e8f5'}}>{spec.secondaryText}</div>:null}</div><div style={{position:'absolute',bottom:130,left:68,width:240,height:5,borderRadius:5,background:'#4ac8e8'}}/></AbsoluteFill>};
const TimelineOrStatisticScene=({visual})=>{const spec=visual.spec;return <AbsoluteFill style={{background:'#111c34',color:'#f5fbff',fontFamily:'Arial,sans-serif',padding:76}}><div style={{fontSize:62,fontWeight:800}}>{spec.title}</div><div style={{marginTop:96,display:'grid',gap:24}}>{(spec.values||[]).map((value,index)=><div key={index} style={{display:'flex',justifyContent:'space-between',borderBottom:'1px solid #5b89a8',paddingBottom:18,fontSize:34}}><span>{value.label}</span><strong>{value.value}</strong></div>)}</div></AbsoluteFill>};
const ChartOrScreenshotScene=({visual})=>{const spec=visual.spec;return <AbsoluteFill style={{background:'linear-gradient(145deg,#101d35,#1f3e58)',color:'#f5fbff',fontFamily:'Arial,sans-serif',padding:76}}><div style={{fontSize:54,fontWeight:800,lineHeight:1.1}}>{spec.intent}</div><div style={{position:'absolute',left:76,right:76,bottom:180,height:310,border:'2px solid #76c7df',borderRadius:20,background:'repeating-linear-gradient(0deg,transparent 0 48px,#76c7df22 49px 50px)'}}/>{(spec.labels||[]).map((label,index)=><div key={index} style={{marginTop:28,fontSize:30,color:'#caeafa'}}>{label}</div>)}</AbsoluteFill>};
const InternalVisualScene=({visual,duration})=>{if(!visual)return null;if(visual.type==='map')return <MapScene visual={visual} duration={duration}/>;if(visual.type==='flow_or_corridor')return <FlowCorridorScene visual={visual} duration={duration}/>;if(visual.type==='text_card')return <TextCardScene visual={visual}/>;if(visual.type==='timeline_or_statistic')return <TimelineOrStatisticScene visual={visual}/>;if(visual.type==='chart_or_screenshot')return <ChartOrScreenshotScene visual={visual}/>;return null;};
`;
