jest.mock('@content-os/storage',()=>({VideoRenderInputRepository:class{},VideoRenderJobRepository:class{}}));
import { access,mkdir,mkdtemp,rm,symlink,writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { Readable } from 'node:stream';
import { VideoRenderWorkerService } from './video-render-worker.service';

describe('VideoRenderWorkerService',()=>{
 const claim={id:'job',attemptId:'attempt',contentScriptId:'script',renderInputManifestId:'manifest',renderInputHash:'hash'};
 const manifest:any={id:'manifest',contentScriptId:'script',inputHash:'hash',sceneCount:2,status:'ready',scenes:[{},{}]};
 const setup=()=>{const bytes=Buffer.from('playable-fixture');const inputs={findByIdentity:jest.fn().mockResolvedValue(manifest)};const jobs={claimNextQueued:jest.fn().mockResolvedValue(claim),reportProgress:jest.fn().mockResolvedValue({}),complete:jest.fn().mockImplementation(async value=>({status:'completed',...value})),fail:jest.fn().mockResolvedValue({status:'failed'}),findByContentScriptId:jest.fn().mockResolvedValue({status:'failed',outputArtifact:null})};const renderer={render:jest.fn(async(_manifest,dir,progress)=>{await progress(1);await progress(2);const path=join(dir,'output.mp4');await writeFile(path,bytes);return {path,durationMs:2000};})};const storage={id:'local',materializeFile:jest.fn().mockResolvedValue(true),resolve:jest.fn(async()=>Readable.from(bytes)),remove:jest.fn().mockResolvedValue(undefined)};return {inputs,jobs,renderer,storage,worker:new VideoRenderWorkerService(inputs as any,jobs as any,renderer as any,storage as any)};};
 it('uses only claimed immutable identity and completes with bounded monotonic progress',async()=>{const state=setup();const result:any=await state.worker.runNext();expect(state.inputs.findByIdentity).toHaveBeenCalledWith('manifest','hash');expect(state.jobs.reportProgress.mock.calls.map(call=>call[0].completedUnits)).toEqual([0,1,2,3]);expect(result.completedUnits).toBe(4);expect(result.totalUnits).toBe(4);expect(result.outputArtifact).toMatchObject({storageProvider:'local',mimeType:'video/mp4',durationMs:2000});expect(result.outputArtifact.checksum).toMatch(/^[a-f0-9]{64}$/);});
 it('fails deterministically without successful artifact persistence when input is missing',async()=>{const state=setup();state.inputs.findByIdentity.mockResolvedValue(undefined);await expect(state.worker.runNext()).resolves.toMatchObject({status:'failed',outputArtifact:null});expect(state.renderer.render).not.toHaveBeenCalled();expect(state.storage.materializeFile).not.toHaveBeenCalled();expect(state.jobs.fail).toHaveBeenCalledWith(expect.objectContaining({attemptId:'attempt',renderInputHash:'hash'}));});
 it('removes materialized bytes when the identity-bound completion is rejected as stale',async()=>{const state=setup();state.jobs.complete.mockRejectedValue(new Error('stale_worker'));await expect(state.worker.runNext()).resolves.toMatchObject({status:'failed'});expect(state.storage.remove).toHaveBeenCalledWith('renders/job/attempt.mp4');});
 it('preserves an existing collision artifact and does not persist success',async()=>{const state=setup();state.storage.materializeFile.mockResolvedValue(false);await expect(state.worker.runNext()).resolves.toMatchObject({status:'failed',outputArtifact:null});expect(state.storage.remove).not.toHaveBeenCalled();expect(state.jobs.complete).not.toHaveBeenCalled();expect(state.jobs.fail).toHaveBeenCalledWith(expect.objectContaining({attemptId:'attempt',renderInputHash:'hash'}));});
 it('removes published bytes and refuses completion when the source changes during publication',async()=>{const state=setup();state.storage.resolve.mockResolvedValue(Readable.from(Buffer.from('mutated-during-copy')));await expect(state.worker.runNext()).resolves.toMatchObject({status:'failed',outputArtifact:null});expect(state.storage.remove).toHaveBeenCalledWith('renders/job/attempt.mp4');expect(state.jobs.complete).not.toHaveBeenCalled();expect(state.jobs.fail).toHaveBeenCalledWith(expect.objectContaining({attemptId:'attempt'}));});
 it('persists failure and cleans local work after an input limit failure',async()=>{const state=setup();state.renderer.render.mockRejectedValue(new Error('input_size_limit'));const workRoot=join(process.cwd(),'.content-os-render-work');await state.worker.runNext();expect(state.jobs.fail).toHaveBeenCalledWith(expect.objectContaining({attemptId:'attempt'}));expect(state.jobs.complete).not.toHaveBeenCalled();await expect(access(join(workRoot,'attempt'))).rejects.toThrow();});
 it('rejects a pre-existing redirected attempt directory without touching its target',async()=>{const state=setup(),sandbox=await mkdtemp(join(tmpdir(),'content-os-worker-')),workRoot=join(sandbox,'work'),outside=join(sandbox,'outside'),previous=process.env.VIDEO_RENDER_WORK_ROOT;await mkdir(workRoot);await mkdir(outside);await writeFile(join(outside,'keep.txt'),'keep');await symlink(outside,join(workRoot,'attempt'),process.platform==='win32'?'junction':'dir');process.env.VIDEO_RENDER_WORK_ROOT=workRoot;try{await expect(state.worker.runNext()).resolves.toMatchObject({status:'failed'});expect(state.renderer.render).not.toHaveBeenCalled();await expect(access(join(outside,'keep.txt'))).resolves.toBeUndefined();}finally{if(previous===undefined)delete process.env.VIDEO_RENDER_WORK_ROOT;else process.env.VIDEO_RENDER_WORK_ROOT=previous;await rm(sandbox,{recursive:true,force:true});}});
});
