import { ConflictException } from '@nestjs/common';
jest.mock('@content-os/contracts',()=>({AudioGenerationStatus:{READY:'ready'},ScenePlanStatus:{READY:'ready'},VideoCompositionAssetStrategy:{SELECTED_CANDIDATE:'selected_candidate',NO_ASSET:'no_asset'},VideoCompositionFailureCode:{SCRIPT_NOT_FOUND:'script_not_found',SCRIPT_NOT_READY:'script_not_ready',SCENE_PLAN_MISSING:'scene_plan_missing',SCENE_PLAN_NOT_READY:'scene_plan_not_ready',AUDIO_MISSING:'audio_missing',AUDIO_NOT_READY:'audio_not_ready',VISUAL_MANIFEST_MISSING:'visual_manifest_missing',VISUAL_MANIFEST_NOT_READY:'visual_manifest_not_ready',IDENTITY_MISMATCH:'identity_mismatch',SCENE_ALIGNMENT_MISMATCH:'scene_alignment_mismatch',AUDIO_TIMING_INVALID:'audio_timing_invalid',VISUAL_REQUIREMENT_MISSING:'visual_requirement_missing',MANUAL_REVIEW_REQUIRED:'manual_review_required',SELECTED_CANDIDATE_MISSING:'selected_candidate_missing',SELECTED_CANDIDATE_INCOMPATIBLE:'selected_candidate_incompatible',PREPARATION_IN_PROGRESS:'preparation_in_progress'},VideoCompositionPlanStatus:{READY:'ready'},VisualAssetManifestStatus:{READY:'ready'},validateInternalVisualSpecification:(value:any)=>value}));
jest.mock('@content-os/storage',()=>({AudioGenerationRepository:class{},ContentScriptRepository:class{},ScenePlanRepository:class{},VideoCompositionRepository:class{},VisualAssetRepository:class{}}));
import { VideoCompositionService } from './video-composition.service';

const fixture=()=>{const scene={id:'scene-1',sceneIndex:0};const script={id:'script-1',projectId:'project-1',status:'ready'};const plan={id:'plan-1',projectId:'project-1',contentScriptId:script.id,status:'ready',inputHash:'plan-hash',scenes:[scene]};const segment={id:'segment-1',sceneId:scene.id,sceneIndex:0,status:'ready',startMs:0,endMs:1000,actualDurationMs:1000};const audio={id:'audio-1',projectId:'project-1',scenePlanId:plan.id,status:'ready',inputHash:'audio-hash',totalDurationMs:1000,segments:[segment]};const candidate={id:'candidate-1',provider:'pexels',providerAssetId:'asset-1',sourceUrl:'https://example.test/a.mp4',mediaIdentity:'media-1',mediaType:'video',mimeType:'video/mp4',width:1080,height:1920,durationMs:2000,checksum:null,licenceType:'pexels',licenceUrl:'https://example.test/license',attributionText:null,commercialUseAllowed:true,modificationAllowed:true,provenanceScore:90,rejectionReasons:[],status:'selected'};const requirement={id:'requirement-1',sceneIndex:0,plannedSceneId:scene.id,requirementType:'stock_footage',acquisitionStrategy:'provider_search',expectedMediaType:'video',selectedCandidateId:candidate.id,licenceRequirements:{commercialUseRequired:true,modificationAllowed:true,attributionRequired:false,provenanceRequired:true,unknownLicenceRequiresManualReview:true},candidates:[candidate]};const manifest={id:'manifest-1',projectId:'project-1',scenePlanId:plan.id,scenePlanInputHash:plan.inputHash,inputHash:'manifest-hash',status:'ready',completedAt:'now',requirements:[requirement]};return {script,plan,audio,manifest};};
const setup=(overrides:any={})=>{const data=fixture();const scripts={findById:jest.fn().mockResolvedValue(data.script)};const plans={findByContentScriptId:jest.fn().mockResolvedValue(data.plan)};const audio={findByContentScriptId:jest.fn().mockResolvedValue(data.audio)};const manifests={findByContentScriptId:jest.fn().mockResolvedValue(data.manifest)};let claimed=false;const compositions={acquirePreparationClaim:jest.fn(async()=>claimed?undefined:(claimed=true,'claim-1')),releasePreparationClaim:jest.fn(async()=>{claimed=false;}),findByContentScriptId:jest.fn().mockResolvedValue(undefined),findSceneById:jest.fn().mockResolvedValue(undefined),upsert:jest.fn(async (plan,scenes)=>({...plan,id:'composition-1',visualAssetManifestId:data.manifest.id,visualManifestInputHash:data.manifest.inputHash,scenePlanId:data.plan.id,scenePlanInputHash:data.plan.inputHash,scenes:scenes.map((scene:any,sceneIndex:number)=>({...scene,id:`composition-scene-${sceneIndex}`,sceneIndex,mediaAssetId:null}))})),bindMediaAsset:jest.fn().mockResolvedValue(true)};const materialization={materialize:jest.fn().mockResolvedValue({id:'media-1',status:'ready',requirementId:'requirement-1',sourceId:'candidate-1'}),findCompatibleReadyAsset:jest.fn().mockImplementation(async(_requirementId:string,_candidateId:string,id:string)=>({id,status:'ready',requirementId:'requirement-1',sourceId:'candidate-1'}))};Object.assign(scripts,overrides.scripts);Object.assign(plans,overrides.plans);Object.assign(audio,overrides.audio);Object.assign(manifests,overrides.manifests);Object.assign(compositions,overrides.compositions);Object.assign(materialization,overrides.materialization);return {data,scripts,plans,audio,manifests,compositions,materialization,service:new VideoCompositionService(scripts as any,plans as any,audio as any,manifests as any,compositions as any,materialization as any)};};
const code=async(promise:Promise<unknown>)=>{try{await promise;}catch(error){return (error as ConflictException).getResponse() as any;}throw new Error('Expected failure');};
describe('VideoCompositionService',()=>{
 it('persists deterministic scene bindings and reuses the same compatible plan',async()=>{const {service,compositions}=setup();const created:any=await service.prepare('script-1');expect(created.scenes[0]).toMatchObject({plannedSceneId:'scene-1',audioSegmentId:'segment-1',audioStartMs:0,audioEndMs:1000,visualRequirementId:'requirement-1',selectedCandidateId:'candidate-1',assetStrategy:'selected_candidate'});expect(created.inputHash).toHaveLength(64);compositions.findByContentScriptId.mockResolvedValue(created);expect((await service.prepare('script-1') as any).id).toBe('composition-1');expect(compositions.upsert).toHaveBeenCalledTimes(1);});
 it('represents an explicit no-asset requirement without a candidate',async()=>{const state=setup();state.data.manifest.requirements[0].acquisitionStrategy='none_required';state.data.manifest.requirements[0].selectedCandidateId=null as any;const result:any=await state.service.prepare('script-1');expect(result.scenes[0]).toMatchObject({assetStrategy:'no_asset',selectedCandidateId:null,candidateIdentityHash:null});});
 it.each(['reusable_template','programmatic_specification'])('represents %s as an internal no-file scene without a candidate',async (strategy)=>{const state=setup();state.data.manifest.requirements[0].acquisitionStrategy=strategy;state.data.manifest.requirements[0].selectedCandidateId=null as any;const result:any=await state.service.prepare('script-1');expect(result.scenes[0]).toMatchObject({assetStrategy:'no_asset',selectedCandidateId:null,candidateIdentityHash:null});expect(state.materialization.materialize).not.toHaveBeenCalled();});
 it.each([['audio_missing','AUDIO_MISSING'],['audio_not_ready','AUDIO_NOT_READY'],['visual_manifest_missing','VISUAL_MANIFEST_MISSING'],['visual_manifest_not_ready','VISUAL_MANIFEST_NOT_READY']])('fails deterministically for %s',async(kind,expected)=>{const state=setup();if(kind==='audio_missing')state.data.audio=null as any;else if(kind==='audio_not_ready')state.data.audio.status='pending';else if(kind==='visual_manifest_missing')state.data.manifest=null as any;else state.data.manifest.status='needs_review';(state.service as any).audio.findByContentScriptId.mockResolvedValue(state.data.audio);(state.service as any).manifests.findByContentScriptId.mockResolvedValue(state.data.manifest);expect((await code(state.service.prepare('script-1'))).code).toBe(expected.toLowerCase());});
 it('rejects alignment and missing selection',async()=>{const first=setup();first.data.audio.segments[0].sceneId='wrong';expect((await code(first.service.prepare('script-1'))).code).toBe('scene_alignment_mismatch');const second=setup();second.data.manifest.requirements[0].selectedCandidateId=null as any;expect((await code(second.service.prepare('script-1'))).code).toBe('selected_candidate_missing');});
 it('rejects a visual requirement that still requires manual review',async()=>{const state=setup();(state.data.manifest.requirements[0] as any).manualReviewRequired=true;expect((await code(state.service.prepare('script-1'))).code).toBe('manual_review_required');});
 it.each([
  ['unresolved candidate rejection reasons',{rejectionReasons:['provenance_review_required']}],
  ['missing provenance score',{provenanceScore:null}],
  ['missing licence metadata',{licenceType:null,licenceUrl:null}],
  ['unknown required rights',{commercialUseAllowed:null}],
 ])('rejects %s',async(_label,override)=>{const state=setup();Object.assign((state.data.manifest.requirements[0] as any).candidates[0],override);expect((await code(state.service.prepare('script-1'))).code).toBe('selected_candidate_incompatible');});
 it('invalidates reuse when the selected candidate identity changes',async()=>{const state=setup();const first:any=await state.service.prepare('script-1');state.compositions.findByContentScriptId.mockResolvedValue(first);state.compositions.upsert.mockClear();(state.data.manifest.requirements[0] as any).candidates[0].providerAssetId='asset-2';const second:any=await state.service.prepare('script-1');expect(state.compositions.upsert).toHaveBeenCalledTimes(1);expect(second.inputHash).not.toBe(first.inputHash);});
 it('regenerates when upstream identity changes',async()=>{const state=setup();const previous={status:'ready',inputHash:'old'};state.compositions.findByContentScriptId.mockResolvedValue(previous);await state.service.prepare('script-1');expect(state.compositions.upsert).toHaveBeenCalled();});
 it('rejects concurrent preparation across independent service instances',async()=>{let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});const state=setup({scripts:{findById:jest.fn(async()=>{await gate;return fixture().script;})}});const second=new VideoCompositionService(state.scripts as any,state.plans as any,state.audio as any,state.manifests as any,state.compositions as any,state.materialization as any);const first=state.service.prepare('script-1');expect((await code(second.prepare('script-1'))).code).toBe('preparation_in_progress');release();await first;});
 it('materializes and persists a compatible selected candidate binding',async()=>{const state=setup();const composition:any=await state.service.prepare('script-1');state.compositions.findByContentScriptId.mockResolvedValue(composition);const result=await state.service.prepareAssets('script-1');expect(result.scenes[0]).toMatchObject({status:'bound',mediaAssetId:'media-1'});expect(state.materialization.materialize).toHaveBeenCalledWith('requirement-1','candidate-1');expect(state.compositions.bindMediaAsset).toHaveBeenCalledWith(composition.scenes[0].id,'candidate-1',composition.scenes[0].candidateIdentityHash,'media-1');});
 it('does not materialize an explicit no-asset scene',async()=>{const state=setup();state.data.manifest.requirements[0].acquisitionStrategy='none_required';state.data.manifest.requirements[0].selectedCandidateId=null as any;const composition:any=await state.service.prepare('script-1');state.compositions.findByContentScriptId.mockResolvedValue(composition);expect((await state.service.prepareAssets('script-1')).scenes[0].status).toBe('no_asset');expect(state.materialization.materialize).not.toHaveBeenCalled();});
 it('reuses a compatible ready binding without materialization',async()=>{const state=setup();const composition:any=await state.service.prepare('script-1');composition.scenes[0].mediaAssetId='media-ready';state.compositions.findByContentScriptId.mockResolvedValue(composition);expect((await state.service.prepareAssets('script-1')).scenes[0].status).toBe('reused');expect(state.materialization.findCompatibleReadyAsset).toHaveBeenCalledWith('requirement-1','candidate-1','media-ready');expect(state.materialization.materialize).not.toHaveBeenCalled();});
 it('reuses the compatible winner when concurrent preparation loses the binding race',async()=>{const state=setup();const composition:any=await state.service.prepare('script-1');state.compositions.findByContentScriptId.mockResolvedValue(composition);let binding:string|null=null;state.compositions.bindMediaAsset.mockImplementation(async(_sceneId:string,_candidateId:string,_hash:string,mediaAssetId:string)=>{if(binding)return false;binding=mediaAssetId;return true;});state.compositions.findSceneById.mockImplementation(async()=>({...composition.scenes[0],mediaAssetId:binding}));const [first,second]=await Promise.all([state.service.prepareAssets('script-1'),state.service.prepareAssets('script-1')]);expect([first.scenes[0].status,second.scenes[0].status].sort()).toEqual(['bound','reused']);expect(first.scenes[0].mediaAssetId).toBe('media-1');expect(second.scenes[0].mediaAssetId).toBe('media-1');expect(binding).toBe('media-1');expect(state.materialization.materialize).toHaveBeenCalledTimes(2);});
 it('rejects stale candidate identity and incompatible existing bindings',async()=>{const stale=setup();const staleComposition:any=await stale.service.prepare('script-1');staleComposition.scenes[0].candidateIdentityHash='stale';stale.compositions.findByContentScriptId.mockResolvedValue(staleComposition);expect((await stale.service.prepareAssets('script-1')).scenes[0].failureCode).toBe('candidate_identity_mismatch');expect(stale.materialization.materialize).not.toHaveBeenCalled();const incompatible=setup({materialization:{findCompatibleReadyAsset:jest.fn().mockResolvedValue(undefined)}});const incompatibleComposition:any=await incompatible.service.prepare('script-1');incompatibleComposition.scenes[0].mediaAssetId='media-bad';incompatible.compositions.findByContentScriptId.mockResolvedValue(incompatibleComposition);expect((await incompatible.service.prepareAssets('script-1')).scenes[0].failureCode).toBe('media_asset_incompatible');expect(incompatible.materialization.materialize).not.toHaveBeenCalled();});
 it('reports conflicts and sanitized failures deterministically',async()=>{const conflict=setup({compositions:{bindMediaAsset:jest.fn().mockResolvedValue(false)}});const composition:any=await conflict.service.prepare('script-1');conflict.compositions.findByContentScriptId.mockResolvedValue(composition);expect((await conflict.service.prepareAssets('script-1')).scenes[0].failureCode).toBe('binding_conflict');const failed=setup({materialization:{materialize:jest.fn().mockRejectedValue(new Error('secret socket details'))}});const failedComposition:any=await failed.service.prepare('script-1');failed.compositions.findByContentScriptId.mockResolvedValue(failedComposition);expect((await failed.service.prepareAssets('script-1')).scenes[0]).toMatchObject({failureCode:'materialization_failed',failureReason:'Media materialization failed'});});
 it('isolates failures from successful scene bindings',async()=>{const state=setup();const composition:any=await state.service.prepare('script-1');composition.scenes.push({...composition.scenes[0],id:'composition-scene-1',sceneIndex:1});state.materialization.materialize.mockResolvedValueOnce({id:'media-1',status:'ready',requirementId:'requirement-1',sourceId:'candidate-1'}).mockRejectedValueOnce(new Error('Media checksum mismatch'));state.compositions.findByContentScriptId.mockResolvedValue(composition);const result=await state.service.prepareAssets('script-1');expect(result.scenes.map(scene=>scene.status)).toEqual(['bound','failed']);expect(result.scenes[1]).toMatchObject({failureCode:'media_validation_failed',failureReason:'Candidate media failed validation'});expect(state.compositions.bindMediaAsset).toHaveBeenCalledTimes(1);});
});
