jest.mock('@content-os/storage',()=>({VideoRenderInputRepository:class{},VideoRenderJobRepository:class{},VideoRenderJobRepositoryError:class extends Error{}}));
jest.mock('@content-os/contracts',()=>({VideoRenderInputManifestStatus:{READY:'ready'},VideoRenderJobStatus:{COMPLETED:'completed'},VideoRenderJobFailureCode:{RENDER_INPUT_NOT_FOUND:'render_input_not_found',RENDER_INPUT_NOT_READY:'render_input_not_ready',RENDER_INPUT_STALE:'render_input_stale',RETRY_NOT_FAILED:'retry_not_failed',ENQUEUE_CONFLICT:'enqueue_conflict'}}));
import { Readable } from 'node:stream';
import { INestApplication, NotFoundException } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { VideoRenderJobController } from './video-render-job.controller';
import { VideoRenderJobService } from './video-render-job.service';

describe('VideoRenderJobController HTTP',()=>{let app:INestApplication;const service={enqueue:jest.fn(),retry:jest.fn(),find:jest.fn(),output:jest.fn()};const id='11111111-1111-4111-8111-111111111111';beforeAll(async()=>{const module=await Test.createTestingModule({controllers:[VideoRenderJobController],providers:[{provide:VideoRenderJobService,useValue:service}]}).compile();app=module.createNestApplication();app.setGlobalPrefix('api');await app.init();});afterAll(()=>app.close());beforeEach(()=>jest.clearAllMocks());
 it('exposes enqueue, retry, and bounded status reads',async()=>{service.enqueue.mockResolvedValue({id:'job',status:'queued'});service.retry.mockResolvedValue({id:'job',attemptNumber:2});service.find.mockResolvedValue({id:'job',progress:{completedUnits:1,totalUnits:2,percent:50}});await request(app.getHttpServer()).post(`/api/content-scripts/${id}/video-render-jobs`).expect(201);await request(app.getHttpServer()).post(`/api/content-scripts/${id}/video-render-jobs/retry`).expect(201);await request(app.getHttpServer()).get(`/api/content-scripts/${id}/video-render-job`).expect(200).expect(({body})=>expect(body.progress.percent).toBe(50));});
 it('validates IDs and preserves not-found behavior',async()=>{await request(app.getHttpServer()).post('/api/content-scripts/nope/video-render-jobs').expect(400);service.find.mockRejectedValue(new NotFoundException());await request(app.getHttpServer()).get(`/api/content-scripts/${id}/video-render-job`).expect(404);});
 it('returns the exact bounded retry conflict response',async()=>{service.retry.mockRejectedValue(new (require('@nestjs/common').ConflictException)({code:'retry_not_failed',message:'Only failed jobs can be retried'}));await request(app.getHttpServer()).post(`/api/content-scripts/${id}/video-render-jobs/retry`).expect(409).expect({code:'retry_not_failed',message:'Only failed jobs can be retried'});});
 it('streams output with persisted bounded headers',async()=>{service.output.mockResolvedValue({stream:Readable.from(Buffer.from('video')),mimeType:'video/mp4',sizeBytes:5});await request(app.getHttpServer()).get(`/api/content-scripts/${id}/video-render-job/output`).expect(200).expect('Content-Type',/video\/mp4/).expect('Content-Length','5').expect('Cache-Control','private, no-store').expect('X-Content-Type-Options','nosniff').expect('Content-Disposition','inline; filename="video-render-output"').expect(res=>expect(res.body).toEqual(Buffer.from('video')));expect(service.output).toHaveBeenCalledWith(id);});
 it('validates output IDs and preserves service rejection responses',async()=>{await request(app.getHttpServer()).get('/api/content-scripts/nope/video-render-job/output').expect(400);service.output.mockRejectedValue(new NotFoundException({code:'video_render_output_missing',message:'Stored video render output was not found'}));await request(app.getHttpServer()).get(`/api/content-scripts/${id}/video-render-job/output`).expect(404).expect({code:'video_render_output_missing',message:'Stored video render output was not found'});});
 it('rejects output from a completed job with stale render-input identity',async()=>{service.output.mockRejectedValue(new (require('@nestjs/common').ConflictException)({code:'render_input_stale',message:'Video render output render-input identity is stale'}));await request(app.getHttpServer()).get(`/api/content-scripts/${id}/video-render-job/output`).expect(409).expect({code:'render_input_stale',message:'Video render output render-input identity is stale'});});
});
