jest.mock('@content-os/storage',()=>({VideoRenderInputRepository:class{},VideoRenderJobRepository:class{},VideoRenderJobRepositoryError:class extends Error{constructor(public code:string,message:string){super(message);}},isValidVideoRenderOutputArtifact:(value:any)=>!!value&&/^[a-z0-9][a-z0-9._-]{0,99}$/.test(value.storageProvider)&&typeof value.storageKey==='string'&&value.storageKey.length>0&&value.storageKey.length<=500&&value.storageKey===value.storageKey.trim()&&!value.storageKey.includes('\\')&&!value.storageKey.startsWith('/')&&!/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(value.storageKey)&&!/[\u0000-\u001f\u007f]/.test(value.storageKey)&&!value.storageKey.split('/').some((segment:string)=>segment===''||segment==='.'||segment==='..')&&['video/mp4','video/webm','video/quicktime'].includes(value.mimeType)&&/^[a-fA-F0-9]{64}$/.test(value.checksum)&&Number.isSafeInteger(value.sizeBytes)&&value.sizeBytes>0&&Number.isSafeInteger(value.durationMs)&&value.durationMs>0}));
jest.mock('@content-os/contracts',()=>({VideoRenderInputManifestStatus:{READY:'ready'},VideoRenderJobStatus:{COMPLETED:'completed'},VideoRenderJobFailureCode:{RENDER_INPUT_NOT_FOUND:'render_input_not_found',RENDER_INPUT_NOT_READY:'render_input_not_ready',RENDER_INPUT_STALE:'render_input_stale',RETRY_NOT_FAILED:'retry_not_failed',ENQUEUE_CONFLICT:'enqueue_conflict'}}));
import { Readable } from 'node:stream';
import { BadGatewayException, BadRequestException, ConflictException, NotFoundException, UnprocessableEntityException } from '@nestjs/common';
import { VideoRenderJobRepositoryError } from '@content-os/storage';
import { VideoRenderJobService } from './video-render-job.service';

describe('VideoRenderJobService',()=>{
 const ready={id:'manifest-1',contentScriptId:'script-1',inputHash:'hash-1',status:'ready'};
 const setup=(manifest:any=ready,current=true)=>{const manifests={findByContentScriptId:jest.fn().mockResolvedValue(manifest)};const jobs={findByContentScriptId:jest.fn(),enqueue:jest.fn().mockResolvedValue({id:'job-1',status:'queued'}),claimNextQueued:jest.fn(),reportProgress:jest.fn(),complete:jest.fn(),fail:jest.fn()};const renderInputs={isCurrent:jest.fn().mockResolvedValue(current)};const storage={id:'local',exists:jest.fn().mockResolvedValue(true),resolve:jest.fn().mockResolvedValue(Readable.from('video'))};return {manifests,jobs,renderInputs,storage,service:new VideoRenderJobService(manifests as any,jobs as any,renderInputs as any,storage as any)};};
 it('queues a READY manifest with its immutable identity',async()=>{const {service,jobs}=setup();await expect(service.enqueue('script-1')).resolves.toMatchObject({status:'queued'});expect(jobs.enqueue).toHaveBeenCalledWith('script-1','manifest-1','hash-1',false);});
 it('rejects missing and failed manifests',async()=>{await expect(setup(null).service.enqueue('script-1')).rejects.toBeInstanceOf(NotFoundException);await expect(setup({...ready,status:'failed'}).service.enqueue('script-1')).rejects.toBeInstanceOf(UnprocessableEntityException);});
 it('rejects a READY manifest after an upstream identity changes',async()=>{const {service,jobs}=setup(ready,false);await expect(service.enqueue('script-1')).rejects.toMatchObject({response:{code:'render_input_stale'}});expect(jobs.enqueue).not.toHaveBeenCalled();});
 it('uses explicit retry and maps an atomic stale check',async()=>{const {service,jobs}=setup();await service.retry('script-1');expect(jobs.enqueue).toHaveBeenCalledWith('script-1','manifest-1','hash-1',true);jobs.enqueue.mockRejectedValue(new VideoRenderJobRepositoryError('render_input_stale','changed'));await expect(service.enqueue('script-1')).rejects.toBeInstanceOf(ConflictException);});
 it('returns a contracted and bounded retry conflict',async()=>{const {service,jobs}=setup();jobs.enqueue.mockRejectedValue(new VideoRenderJobRepositoryError('retry_not_failed','Only failed jobs can be retried'));await expect(service.retry('script-1')).rejects.toMatchObject({status:409,response:{code:'retry_not_failed',message:'Only failed jobs can be retried'}});});
 it('returns the current job and reports missing status',async()=>{const {service,jobs}=setup();jobs.findByContentScriptId.mockResolvedValueOnce({id:'job'}).mockResolvedValueOnce(undefined);await expect(service.find('script-1')).resolves.toEqual({id:'job'});await expect(service.find('script-1')).rejects.toBeInstanceOf(NotFoundException);});
 it('resolves only the persisted artifact of the current completed job',async()=>{const {service,jobs,storage}=setup();const artifact={storageProvider:'local',storageKey:'renders/job/output.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:5,durationMs:1000};jobs.findByContentScriptId.mockResolvedValue({status:'completed',renderInputManifestId:'manifest-1',renderInputHash:'hash-1',outputArtifact:artifact});await expect(service.output('script-1')).resolves.toMatchObject({mimeType:'video/mp4',sizeBytes:5});expect(storage.exists).toHaveBeenCalledWith(artifact.storageKey);expect(storage.resolve).toHaveBeenCalledWith(artifact.storageKey);});
 it('rejects a completed job whose persisted render-input identity is stale',async()=>{const {service,jobs,renderInputs,storage}=setup();jobs.findByContentScriptId.mockResolvedValue({status:'completed',renderInputManifestId:'manifest-1',renderInputHash:'old-hash',outputArtifact:{storageProvider:'local',storageKey:'renders/job/output.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:5,durationMs:1000}});await expect(service.output('script-1')).rejects.toMatchObject({status:409,response:{code:'render_input_stale'}});expect(renderInputs.isCurrent).not.toHaveBeenCalled();expect(storage.exists).not.toHaveBeenCalled();expect(storage.resolve).not.toHaveBeenCalled();});
 it.each(['queued','running','failed','stale'])('rejects a %s current attempt',async status=>{const {service,jobs,storage}=setup();jobs.findByContentScriptId.mockResolvedValue({status,outputArtifact:null});await expect(service.output('script-1')).rejects.toMatchObject({status:409});expect(storage.resolve).not.toHaveBeenCalled();});
 it('maps missing jobs, artifacts, objects, and storage failures deterministically',async()=>{const state=setup();const identity={renderInputManifestId:'manifest-1',renderInputHash:'hash-1'};state.jobs.findByContentScriptId.mockResolvedValueOnce(undefined).mockResolvedValue({status:'completed',...identity,outputArtifact:null});await expect(state.service.output('script-1')).rejects.toBeInstanceOf(NotFoundException);await expect(state.service.output('script-1')).rejects.toMatchObject({response:{code:'video_render_output_missing'}});const outputArtifact={storageProvider:'local',storageKey:'renders/job/output.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:5,durationMs:1000};state.jobs.findByContentScriptId.mockResolvedValue({status:'completed',...identity,outputArtifact});state.storage.exists.mockResolvedValueOnce(false).mockRejectedValueOnce(new Error('offline')).mockResolvedValue(true);await expect(state.service.output('script-1')).rejects.toMatchObject({status:404});await expect(state.service.output('script-1')).rejects.toBeInstanceOf(BadGatewayException);state.storage.resolve.mockRejectedValue(new Error('read failed'));await expect(state.service.output('script-1')).rejects.toMatchObject({response:{code:'video_render_storage_failure'}});});
 it('exposes worker claim and identity-bound transitions',async()=>{const {service,jobs}=setup();const identity={jobId:'job-1',attemptId:'attempt-1',renderInputManifestId:'manifest-1',renderInputHash:'hash-1'};const outputArtifact={storageProvider:'local',storageKey:'renders/job-1/output.mp4',mimeType:'video/mp4' as const,checksum:'a'.repeat(64),sizeBytes:1024,durationMs:1000};jobs.claimNextQueued.mockResolvedValue({id:'job-1',status:'running'});jobs.reportProgress.mockResolvedValue({status:'running'});jobs.complete.mockResolvedValue({status:'completed'});jobs.fail.mockResolvedValue({status:'failed'});await expect(service.claimNextQueued()).resolves.toMatchObject({status:'running'});await service.reportProgress({...identity,completedUnits:1,totalUnits:2});await service.complete({...identity,completedUnits:2,totalUnits:2,outputArtifact});await service.fail({...identity,message:'secret payload'});expect(jobs.reportProgress).toHaveBeenCalledWith({...identity,completedUnits:1,totalUnits:2});expect(jobs.complete).toHaveBeenCalledWith({...identity,completedUnits:2,totalUnits:2,outputArtifact});expect(jobs.fail).toHaveBeenCalledWith({...identity,message:'secret payload'});});
 it.each([
  ['missing',undefined],['non-video',{storageProvider:'local',storageKey:'renders/out.mp4',mimeType:'image/png',checksum:'a'.repeat(64),sizeBytes:1,durationMs:1}],['filesystem path',{storageProvider:'local',storageKey:'C:\\private\\out.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:1,durationMs:1}],['Windows forward-slash path',{storageProvider:'local',storageKey:'C:/private/out.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:1,durationMs:1}],['file URI',{storageProvider:'local',storageKey:'file:///private/out.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:1,durationMs:1}],['URI scheme',{storageProvider:'local',storageKey:'https://storage.invalid/out.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:1,durationMs:1}],['control character',{storageProvider:'local',storageKey:'renders/private\n/out.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:1,durationMs:1}],['non-normalized segment',{storageProvider:'local',storageKey:'renders/./out.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:1,durationMs:1}],['bad checksum',{storageProvider:'local',storageKey:'renders/out.mp4',mimeType:'video/mp4',checksum:'bad',sizeBytes:1,durationMs:1}],['zero size',{storageProvider:'local',storageKey:'renders/out.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:0,durationMs:1}],['invalid duration',{storageProvider:'local',storageKey:'renders/out.mp4',mimeType:'video/mp4',checksum:'a'.repeat(64),sizeBytes:1,durationMs:0}]
 ])('rejects %s output artifact metadata before persistence',(_label,outputArtifact)=>{const {service,jobs}=setup();expect(()=>service.complete({jobId:'job',attemptId:'attempt',renderInputManifestId:'manifest',renderInputHash:'hash',completedUnits:1,totalUnits:1,outputArtifact} as any)).toThrow(BadRequestException);expect(jobs.complete).not.toHaveBeenCalled();});
 it('reports an empty worker queue deterministically',async()=>{const {service,jobs}=setup();jobs.claimNextQueued.mockResolvedValue(undefined);await expect(service.claimNextQueued()).rejects.toBeInstanceOf(NotFoundException);});
});
