import { createHash } from 'node:crypto';
import { ConflictException } from '@nestjs/common';
jest.mock('@content-os/contracts',()=>({AudioGenerationStatus:{READY:'ready'},VideoCompositionAssetStrategy:{SELECTED_CANDIDATE:'selected_candidate',NO_ASSET:'no_asset'},VideoCompositionPlanStatus:{READY:'ready'},VideoRenderInputManifestStatus:{READY:'ready',FAILED:'failed'},VisualAssetManifestStatus:{READY:'ready'},VideoRenderInputFailureCode:{COMPOSITION_NOT_FOUND:'composition_not_found',COMPOSITION_NOT_READY:'composition_not_ready',COMPOSITION_STALE:'composition_stale',AUDIO_NOT_FOUND:'audio_not_found',AUDIO_NOT_READY:'audio_not_ready',AUDIO_STALE:'audio_stale',AUDIO_OUTPUT_MISSING:'audio_output_missing',AUDIO_SEGMENT_INVALID:'audio_segment_invalid',CANDIDATE_STALE:'candidate_stale',MEDIA_ASSET_MISSING:'media_asset_missing',MEDIA_ASSET_NOT_READY:'media_asset_not_ready',MEDIA_ASSET_INCOMPATIBLE:'media_asset_incompatible'}}));
jest.mock('@content-os/storage',()=>({AudioGenerationRepository:class{},MediaAssetRepository:class{},VideoCompositionRepository:class{},VideoMotionRepository:class{},VideoRenderInputRepository:class{},VisualAssetRepository:class{}}));
import { VideoRenderInputService } from './video-render-input.service';
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const fixture=()=>{const candidate:any={id:'candidate',provider:'pexels',providerAssetId:'asset',sourceUrl:'https://x.test/a.mp4',mediaIdentity:'source',mediaType:'video',mimeType:'video/mp4',width:1080,height:1920,durationMs:2000,checksum:null,licenceType:'stock',licenceUrl:'https://x.test/license',attributionText:null,commercialUseAllowed:true,modificationAllowed:true,provenanceScore:90,rejectionReasons:[],status:'selected'};const candidateIdentityHash=hash(candidate);const scene:any={id:'composition-scene',sceneIndex:0,plannedSceneId:'planned-scene',audioSegmentId:'segment',audioStartMs:0,audioEndMs:1000,audioDurationMs:1000,visualRequirementId:'requirement',assetStrategy:'selected_candidate',selectedCandidateId:'candidate',candidateIdentityHash,mediaAssetId:'media'};const composition:any={id:'composition',projectId:'project',contentScriptId:'11111111-1111-4111-8111-111111111111',scenePlanId:'plan',scenePlanInputHash:'plan-hash',audioGenerationId:'audio',audioInputHash:'audio-hash',visualAssetManifestId:'visual',visualManifestInputHash:'visual-hash',inputHash:'composition-hash',status:'ready',totalDurationMs:1000,sceneCount:1,scenes:[scene]};const audio:any={id:'audio',scenePlanId:'plan',inputHash:'audio-hash',status:'ready',outputPath:null,totalDurationMs:1000,segments:[{id:'segment',sceneId:'planned-scene',sceneIndex:0,status:'ready',audioPath:'audio/segment.wav',startMs:0,endMs:1000,actualDurationMs:1000}]};const visual:any={id:'visual',scenePlanId:'plan',scenePlanInputHash:'plan-hash',inputHash:'visual-hash',status:'ready',requirements:[{id:'requirement',selectedCandidateId:'candidate',candidates:[candidate]}]};const asset:any={id:'media',status:'ready',sourceType:'visual_asset_candidate',sourceId:'candidate',requirementId:'requirement',mediaType:'video',mimeType:'video/mp4',storageProvider:'local',storageKey:'video/a.mp4',checksum:'abc'};return {composition,audio,visual,asset};};
const setup=()=>{const data=fixture();const repositories:any={compositions:{findByContentScriptId:jest.fn().mockResolvedValue(data.composition)},audio:{findByContentScriptId:jest.fn().mockResolvedValue(data.audio)},visuals:{findByContentScriptId:jest.fn().mockResolvedValue(data.visual)},motions:{findByContentScriptId:jest.fn()},materialization:{findCompatibleReadyAsset:jest.fn().mockResolvedValue(data.asset)},manifests:{findByContentScriptId:jest.fn(),upsert:jest.fn(async(d,s)=>({...d,id:'render-manifest',scenes:s.map((x:any,i:number)=>({...x,id:`input-${i}`,sceneIndex:i}))}))}};return {data,...repositories,service:new VideoRenderInputService(repositories.compositions,repositories.audio,repositories.visuals,repositories.materialization,repositories.manifests,repositories.motions)};};
const failure=async(p:Promise<unknown>)=>{try{await p;}catch(error){return (error as ConflictException).getResponse() as any;}throw new Error('expected failure');};
describe('VideoRenderInputService',()=>{
 it('detects a captured manifest identity made stale by an upstream change',async()=>{const state=setup();const manifest={contentScriptId:state.data.composition.contentScriptId,compositionPlanId:'composition',compositionInputHash:'composition-hash',audioGenerationId:'audio',audioInputHash:'audio-hash',visualAssetManifestId:'visual',visualManifestInputHash:'visual-hash'};await expect(state.service.isCurrent(manifest)).resolves.toBe(true);state.data.audio.inputHash='changed';await expect(state.service.isCurrent(manifest)).resolves.toBe(false);});
 it('persists ordered renderer-neutral inputs and reuses an identical ready manifest',async()=>{const state=setup();const first:any=await state.service.prepare(state.data.composition.contentScriptId);expect(first.scenes[0]).toMatchObject({startMs:0,endMs:1000,audioPath:'audio/segment.wav',mediaAssetId:'media',storageKey:'video/a.mp4'});state.manifests.findByContentScriptId.mockResolvedValue(first);expect((await state.service.prepare(state.data.composition.contentScriptId) as any).id).toBe('render-manifest');expect(state.manifests.upsert).toHaveBeenCalledTimes(1);});
 it('preserves an explicit no-asset scene',async()=>{const state=setup();Object.assign(state.data.composition.scenes[0],{assetStrategy:'no_asset',selectedCandidateId:null,candidateIdentityHash:null,mediaAssetId:null});const result:any=await state.service.prepare(state.data.composition.contentScriptId);expect(result.scenes[0]).toMatchObject({assetStrategy:'no_asset',mediaAssetId:null,storageKey:null});expect(state.materialization.findCompatibleReadyAsset).not.toHaveBeenCalled();});
 it('carries a compatible validated motion plan without changing scene timing',async()=>{const state=setup();state.motions.findByContentScriptId.mockResolvedValue({id:'motion',status:'ready',inputHash:'motion-hash',videoCompositionPlanId:'composition',compositionInputHash:'composition-hash',scenes:[{sceneIndex:0,compositionSceneId:'composition-scene',plannedSceneId:'planned-scene',cameraMotion:'zoom_in',transition:'cut',overlays:[],map:null}]});const result:any=await state.service.prepare(state.data.composition.contentScriptId);expect(result.videoMotionPlanId).toBe('motion');expect(result.scenes[0]).toMatchObject({durationMs:1000,motion:{cameraMotion:'zoom_in',transition:'cut'}});});
 it.each([['missing segment output','audio_segment_invalid',(s:any)=>s.data.audio.segments[0].audioPath=''],['stale audio','audio_stale',(s:any)=>s.data.audio.inputHash='changed'],['stale candidate','candidate_stale',(s:any)=>s.data.visual.requirements[0].candidates[0].providerAssetId='changed'],['missing media','media_asset_missing',(s:any)=>s.data.composition.scenes[0].mediaAssetId=null],['missing stored media','media_asset_incompatible',(s:any)=>s.materialization.findCompatibleReadyAsset.mockResolvedValue(undefined)]])('persists sanitized failure for %s',async(_label,code,mutate)=>{const state=setup();mutate(state);expect((await failure(state.service.prepare(state.data.composition.contentScriptId))).code).toBe(code);expect(state.manifests.upsert).toHaveBeenLastCalledWith(expect.objectContaining({status:'failed',failureCode:code}),[]);});
 it('rejects a visual manifest that is no longer ready',async()=>{const state=setup();state.data.visual.status='stale';expect((await failure(state.service.prepare(state.data.composition.contentScriptId))).code).toBe('composition_stale');});
 it.each([['gap',1100,2100],['overlap',900,1900]])('rejects a multi-scene timeline with a %s',async(_label,startMs,endMs)=>{const state=setup();const first=state.data.composition.scenes[0];const second={...first,id:'composition-scene-2',sceneIndex:1,plannedSceneId:'planned-scene-2',audioSegmentId:'segment-2',audioStartMs:startMs,audioEndMs:endMs};state.data.composition.scenes.push(second);state.data.composition.sceneCount=2;state.data.composition.totalDurationMs=endMs;state.data.audio.segments.push({id:'segment-2',sceneId:'planned-scene-2',sceneIndex:1,status:'ready',audioPath:'audio/segment-2.wav',startMs,endMs,actualDurationMs:1000});state.data.audio.totalDurationMs=endMs;expect((await failure(state.service.prepare(state.data.composition.contentScriptId))).code).toBe('audio_segment_invalid');});
 it('regenerates when a ready manifest has a stale input identity',async()=>{const state=setup();state.manifests.findByContentScriptId.mockResolvedValue({status:'ready',inputHash:'old'});await state.service.prepare(state.data.composition.contentScriptId);expect(state.manifests.upsert).toHaveBeenCalledTimes(1);});
});
