import type { ResolvedGeographicReference } from './geographic-reference.js';
export type InternalVisualType = 'map' | 'flow_or_corridor' | 'text_card' | 'timeline_or_statistic' | 'chart_or_screenshot';
export type InternalVisualPoint = { latitude: number; longitude: number };
export type InternalVisualMarker = InternalVisualPoint & { id?: string; label?: string; role?: 'focus' | 'context'; emphasis?: 'primary' | 'secondary' };
export type InternalVisualRoute = { id?: string; points: InternalVisualPoint[]; label?: string; role?: 'primary' | 'context'; direction?: 'forward' | 'reverse' | 'bidirectional' };
export type InternalVisualNamedRegion = { id: string; label: string; geometryStatus: 'named_region' | 'unavailable'; emphasis: 'primary' | 'secondary' };
export type InternalVisualZone = { id: string; label: string; kind: 'chokepoint' | 'pressure' | 'blockade' | 'focus'; geometryStatus: 'named_region' | 'unavailable'; emphasis: 'primary' | 'secondary' };
export type InternalVisualViewport = { framing: 'close' | 'regional' | 'wide' | 'auto'; geometryStatus: 'coordinate' | 'bounds' | 'named_region' | 'unavailable' };
export type InternalVisualFlowEntity = { id: string; kind: 'generic'; count: number };
export type InternalVisualFlowLane = { id: string; role: 'primary' | 'context'; geometryStatus: 'coordinate' | 'unavailable' };
export type InternalVisualFlowPressure = { id: string; label: string; kind: 'pressure' | 'blockade' | 'chokepoint' };

export type InternalVisualSpecification =
  | { type: 'map'; version: 'internal-visual-v1'; spec: { focus: string; viewport: InternalVisualViewport; highlightedRegions: string[]; regionDetails: InternalVisualNamedRegion[]; geographicReferences: ResolvedGeographicReference[]; markers: InternalVisualMarker[]; routes: InternalVisualRoute[]; zones: InternalVisualZone[]; labels: string[]; emphasisTargets: string[] } }
  | { type: 'flow_or_corridor'; version: 'internal-visual-v1'; spec: { direction: 'forward' | 'reverse' | 'bidirectional'; lanes: InternalVisualRoute[]; laneConfiguration: InternalVisualFlowLane[]; movingEntities: string[]; entityConfiguration: InternalVisualFlowEntity[]; compression: 'none' | 'slowdown' | 'pressure'; progression: 'steady' | 'approach' | 'pulse'; pressureZone: string | null; pressureZoneDetails: InternalVisualFlowPressure | null; labels: string[]; emphasisTargets: string[] } }
  | { type: 'text_card'; version: 'internal-visual-v1'; spec: { primaryText: string; secondaryText: string | null; emphasis: 'none' | 'primary' | 'statistic'; layout: 'centered' | 'headline' | 'split' } }
  | { type: 'timeline_or_statistic'; version: 'internal-visual-v1'; spec: { title: string; values: Array<{ label: string; value: string }>; labels: string[]; emphasisTarget: string | null } }
  | { type: 'chart_or_screenshot'; version: 'internal-visual-v1'; spec: { intent: string; labels: string[]; dataReferences: string[] } };

const asText = (value: unknown, max = 240): string | null => typeof value === 'string' && value.trim().length > 0 && value.trim().length <= max ? value.trim() : null;
const id = (value: unknown, fallback: string) => asText(value, 120) ?? (fallback.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'item');
const textList = (value: unknown, max = 12, length = 160) => { if (!Array.isArray(value) || value.length > max) throw new Error('Internal visual text list is invalid'); const normalized = value.map((item) => asText(item, length)); if (normalized.some((item) => item === null)) throw new Error('Internal visual text list is invalid'); return [...new Set(normalized as string[])]; };
const point = (value: unknown): InternalVisualPoint | null => { if (!value || typeof value !== 'object') return null; const latitude = Reflect.get(value, 'latitude'); const longitude = Reflect.get(value, 'longitude'); return Number.isFinite(latitude) && Number.isFinite(longitude) && Number(latitude) >= -90 && Number(latitude) <= 90 && Number(longitude) >= -180 && Number(longitude) <= 180 ? { latitude: Number(latitude), longitude: Number(longitude) } : null; };
const enumValue = <T extends string>(value: unknown, values: readonly T[], message: string): T => { if (!values.includes(String(value) as T)) throw new Error(message); return value as T; };
const routes = (value: unknown): InternalVisualRoute[] => { if (!Array.isArray(value) || value.length > 8) throw new Error('Internal visual routes are invalid'); return value.map((route) => { if (!route || typeof route !== 'object' || !Array.isArray(Reflect.get(route, 'points'))) throw new Error('Internal visual route is invalid'); const points = (Reflect.get(route, 'points') as unknown[]).map(point); if (points.length < 2 || points.length > 24 || points.some((item) => item === null)) throw new Error('Internal visual route is invalid'); const label = asText(Reflect.get(route, 'label'), 120); const role = Reflect.get(route, 'role') == null ? undefined : enumValue(Reflect.get(route, 'role'), ['primary', 'context'] as const, 'Internal visual route role is invalid'); const direction = Reflect.get(route, 'direction') == null ? undefined : enumValue(Reflect.get(route, 'direction'), ['forward', 'reverse', 'bidirectional'] as const, 'Internal visual route direction is invalid'); return { id: id(Reflect.get(route, 'id'), label ?? 'route'), points: points as InternalVisualPoint[], ...(label ? { label } : {}), ...(role ? { role } : {}), ...(direction ? { direction } : {}) }; }); };
const markers = (value: unknown): InternalVisualMarker[] => { if (!Array.isArray(value) || value.length > 24) throw new Error('Internal visual markers are invalid'); return value.map((marker) => { const coordinate = point(marker); if (!coordinate || !marker || typeof marker !== 'object') throw new Error('Internal visual marker is invalid'); const label = asText(Reflect.get(marker, 'label'), 120); const role = Reflect.get(marker, 'role') == null ? undefined : enumValue(Reflect.get(marker, 'role'), ['focus', 'context'] as const, 'Internal visual marker role is invalid'); const emphasis = Reflect.get(marker, 'emphasis') == null ? undefined : enumValue(Reflect.get(marker, 'emphasis'), ['primary', 'secondary'] as const, 'Internal visual marker emphasis is invalid'); return { id: id(Reflect.get(marker, 'id'), label ?? 'marker'), ...coordinate, ...(label ? { label } : {}), ...(role ? { role } : {}), ...(emphasis ? { emphasis } : {}) }; }); };
const regions = (value: unknown): InternalVisualNamedRegion[] => { if (!Array.isArray(value) || value.length > 12) throw new Error('Internal visual regions are invalid'); return value.map((item) => { if (typeof item === 'string') { const label = asText(item, 160); if (!label) throw new Error('Internal visual region is invalid'); return { id: id(null, label), label, geometryStatus: 'named_region', emphasis: 'secondary' }; } if (!item || typeof item !== 'object') throw new Error('Internal visual region is invalid'); const label = asText(Reflect.get(item, 'label'), 160); if (!label) throw new Error('Internal visual region is invalid'); return { id: id(Reflect.get(item, 'id'), label), label, geometryStatus: enumValue(Reflect.get(item, 'geometryStatus'), ['named_region', 'unavailable'] as const, 'Internal visual region is invalid'), emphasis: enumValue(Reflect.get(item, 'emphasis'), ['primary', 'secondary'] as const, 'Internal visual region is invalid') }; }); };
const zones = (value: unknown): InternalVisualZone[] => { if (!Array.isArray(value) || value.length > 12) throw new Error('Internal visual zones are invalid'); return value.map((item) => { if (!item || typeof item !== 'object') throw new Error('Internal visual zone is invalid'); const label = asText(Reflect.get(item, 'label'), 160); if (!label) throw new Error('Internal visual zone is invalid'); return { id: id(Reflect.get(item, 'id'), label), label, kind: enumValue(Reflect.get(item, 'kind'), ['chokepoint', 'pressure', 'blockade', 'focus'] as const, 'Internal visual zone is invalid'), geometryStatus: enumValue(Reflect.get(item, 'geometryStatus'), ['named_region', 'unavailable'] as const, 'Internal visual zone is invalid'), emphasis: enumValue(Reflect.get(item, 'emphasis'), ['primary', 'secondary'] as const, 'Internal visual zone is invalid') }; }); };
const viewport = (value: unknown): InternalVisualViewport => { if (value == null) return { framing: 'auto', geometryStatus: 'unavailable' }; if (!value || typeof value !== 'object') throw new Error('Internal visual viewport is invalid'); return { framing: enumValue(Reflect.get(value, 'framing'), ['close', 'regional', 'wide', 'auto'] as const, 'Internal visual viewport is invalid'), geometryStatus: enumValue(Reflect.get(value, 'geometryStatus'), ['coordinate', 'bounds', 'named_region', 'unavailable'] as const, 'Internal visual viewport is invalid') }; };
const flowLanes = (value: unknown): InternalVisualFlowLane[] => { if (!Array.isArray(value) || value.length > 8) throw new Error('Internal flow lane configuration is invalid'); return value.map((item) => { if (!item || typeof item !== 'object') throw new Error('Internal flow lane configuration is invalid'); const laneId = asText(Reflect.get(item, 'id'), 120); if (!laneId) throw new Error('Internal flow lane configuration is invalid'); return { id: laneId, role: enumValue(Reflect.get(item, 'role'), ['primary', 'context'] as const, 'Internal flow lane configuration is invalid'), geometryStatus: enumValue(Reflect.get(item, 'geometryStatus'), ['coordinate', 'unavailable'] as const, 'Internal flow lane configuration is invalid') }; }); };
const flowEntities = (value: unknown): InternalVisualFlowEntity[] => { if (!Array.isArray(value) || value.length > 12) throw new Error('Internal flow entities are invalid'); return value.map((item) => { if (!item || typeof item !== 'object') throw new Error('Internal flow entity is invalid'); const entityId = asText(Reflect.get(item, 'id'), 120); const count = Reflect.get(item, 'count'); if (!entityId || Reflect.get(item, 'kind') !== 'generic' || !Number.isInteger(count) || Number(count) < 1 || Number(count) > 12) throw new Error('Internal flow entity is invalid'); return { id: entityId, kind: 'generic', count: Number(count) }; }); };
const pressure = (value: unknown): InternalVisualFlowPressure | null => { if (value == null) return null; if (typeof value === 'string') { const label = asText(value, 160); if (!label) throw new Error('Internal flow pressure zone is invalid'); return { id: id(null, label), label, kind: 'pressure' }; } if (!value || typeof value !== 'object') throw new Error('Internal flow pressure zone is invalid'); const label = asText(Reflect.get(value, 'label'), 160); if (!label) throw new Error('Internal flow pressure zone is invalid'); return { id: id(Reflect.get(value, 'id'), label), label, kind: enumValue(Reflect.get(value, 'kind'), ['pressure', 'blockade', 'chokepoint'] as const, 'Internal flow pressure zone is invalid') }; };

/** Validates and normalizes a persisted, renderer-independent internal visual snapshot. */
export function validateInternalVisualSpecification(value: unknown): InternalVisualSpecification {
  if (!value || typeof value !== 'object' || Reflect.get(value, 'version') !== 'internal-visual-v1') throw new Error('Internal visual specification is invalid');
  const type = Reflect.get(value, 'type'); const spec = Reflect.get(value, 'spec'); if (!spec || typeof spec !== 'object') throw new Error('Internal visual specification is invalid');
  if (type === 'map') { const focus = asText(Reflect.get(spec, 'focus'), 160); if (!focus) throw new Error('Internal map focus is invalid'); const regionDetails = regions(Reflect.get(spec, 'regionDetails') ?? []); const geographicReferences = Array.isArray(Reflect.get(spec, 'geographicReferences')) ? Reflect.get(spec, 'geographicReferences') as ResolvedGeographicReference[] : []; return { type, version: 'internal-visual-v1', spec: { focus, viewport: viewport(Reflect.get(spec, 'viewport')), highlightedRegions: textList(Reflect.get(spec, 'highlightedRegions') ?? regionDetails.map((region) => region.label)), regionDetails, geographicReferences, markers: markers(Reflect.get(spec, 'markers') ?? []), routes: routes(Reflect.get(spec, 'routes') ?? []), zones: zones(Reflect.get(spec, 'zones') ?? []), labels: textList(Reflect.get(spec, 'labels') ?? []), emphasisTargets: textList(Reflect.get(spec, 'emphasisTargets') ?? []) } }; }
  if (type === 'flow_or_corridor') { const direction = enumValue(Reflect.get(spec, 'direction'), ['forward', 'reverse', 'bidirectional'] as const, 'Internal flow direction is invalid'); const compression = enumValue(Reflect.get(spec, 'compression') ?? 'none', ['none', 'slowdown', 'pressure'] as const, 'Internal flow configuration is invalid'); const progression = enumValue(Reflect.get(spec, 'progression') ?? 'steady', ['steady', 'approach', 'pulse'] as const, 'Internal flow configuration is invalid'); const pressureZoneDetails = pressure(Reflect.get(spec, 'pressureZoneDetails') ?? Reflect.get(spec, 'pressureZone')); return { type, version: 'internal-visual-v1', spec: { direction, lanes: routes(Reflect.get(spec, 'lanes') ?? []), laneConfiguration: flowLanes(Reflect.get(spec, 'laneConfiguration') ?? []), movingEntities: textList(Reflect.get(spec, 'movingEntities') ?? []), entityConfiguration: flowEntities(Reflect.get(spec, 'entityConfiguration') ?? []), compression, progression, pressureZone: pressureZoneDetails?.label ?? null, pressureZoneDetails, labels: textList(Reflect.get(spec, 'labels') ?? []), emphasisTargets: textList(Reflect.get(spec, 'emphasisTargets') ?? []) } }; }
  if (type === 'text_card') { const primaryText = asText(Reflect.get(spec, 'primaryText'), 300); const secondary = Reflect.get(spec, 'secondaryText'); const secondaryText = secondary == null ? null : asText(secondary, 300); if (!primaryText || (secondary != null && !secondaryText)) throw new Error('Internal text card is invalid'); return { type, version: 'internal-visual-v1', spec: { primaryText, secondaryText, emphasis: enumValue(Reflect.get(spec, 'emphasis'), ['none', 'primary', 'statistic'] as const, 'Internal text card is invalid'), layout: enumValue(Reflect.get(spec, 'layout'), ['centered', 'headline', 'split'] as const, 'Internal text card is invalid') } }; }
  if (type === 'timeline_or_statistic') { const title = asText(Reflect.get(spec, 'title'), 240); const values = Reflect.get(spec, 'values'); if (!title || !Array.isArray(values) || values.length > 12) throw new Error('Internal timeline is invalid'); const normalized = values.map((item) => { const label = item && typeof item === 'object' ? asText(Reflect.get(item, 'label'), 120) : null; const entry = item && typeof item === 'object' ? asText(Reflect.get(item, 'value'), 120) : null; if (!label || !entry) throw new Error('Internal timeline is invalid'); return { label, value: entry }; }); const emphasis = Reflect.get(spec, 'emphasisTarget'); const emphasisTarget = emphasis == null ? null : asText(emphasis, 120); if (emphasis != null && !emphasisTarget) throw new Error('Internal timeline is invalid'); return { type, version: 'internal-visual-v1', spec: { title, values: normalized, labels: textList(Reflect.get(spec, 'labels') ?? []), emphasisTarget } }; }
  if (type === 'chart_or_screenshot') { const intent = asText(Reflect.get(spec, 'intent'), 500); if (!intent) throw new Error('Internal chart intent is invalid'); return { type, version: 'internal-visual-v1', spec: { intent, labels: textList(Reflect.get(spec, 'labels') ?? []), dataReferences: textList(Reflect.get(spec, 'dataReferences') ?? [], 24, 160) } }; }
  throw new Error('Internal visual type is invalid');
}
