import type { VideoCompositionAssetStrategy, VideoCompositionFailureCode, VideoCompositionPlanStatus } from './enums.js';

export interface VideoCompositionIdentity { contentScriptId: string; scenePlanId: string; scenePlanInputHash: string; audioGenerationId: string; audioInputHash: string; visualAssetManifestId: string; visualManifestInputHash: string; }
export interface VideoCompositionScene { id: string; compositionPlanId: string; sceneIndex: number; plannedSceneId: string; audioSegmentId: string; audioStartMs: number; audioEndMs: number; audioDurationMs: number; visualRequirementId: string; visualRequirementType: string; assetStrategy: VideoCompositionAssetStrategy; selectedCandidateId: string | null; candidateIdentityHash: string | null; mediaAssetId: string | null; createdAt: string; }
export interface VideoCompositionPlan extends VideoCompositionIdentity { id: string; projectId: string; version: string; inputHash: string; status: VideoCompositionPlanStatus; totalDurationMs: number; sceneCount: number; failureCode: VideoCompositionFailureCode | null; failureReason: string | null; createdAt: string; updatedAt: string; scenes: VideoCompositionScene[]; }
export type VideoCompositionSceneAssetPreparationStatus = 'bound' | 'reused' | 'no_asset' | 'failed';
export type VideoCompositionSceneAssetPreparationFailureCode = 'candidate_identity_mismatch' | 'media_asset_incompatible' | 'binding_conflict' | 'candidate_not_eligible' | 'rights_policy_blocked' | 'source_validation_failed' | 'media_validation_failed' | 'materialization_failed';
export interface VideoCompositionSceneAssetPreparationResult { sceneId: string; sceneIndex: number; status: VideoCompositionSceneAssetPreparationStatus; mediaAssetId: string | null; failureCode: VideoCompositionSceneAssetPreparationFailureCode | null; failureReason: string | null; }
export interface VideoCompositionAssetPreparationResult { compositionPlanId: string; scenes: VideoCompositionSceneAssetPreparationResult[]; }
