import type { VideoCompositionAssetStrategy, VideoRenderInputFailureCode, VideoRenderInputManifestStatus, VideoRenderJobFailureCode, VideoRenderJobStatus } from './enums.js';
import type { InternalVisualSpecification } from './internal-visual.js';
import type { VideoCameraMotion, VideoMotionMapChoreography, VideoMotionOverlay, VideoTransition } from './video-motion.js';

export interface VideoRenderInputIdentity { compositionPlanId: string; compositionInputHash: string; audioGenerationId: string; audioInputHash: string; visualAssetManifestId: string; visualManifestInputHash: string; videoMotionPlanId?: string | null; videoMotionInputHash?: string | null; }
export interface VideoRenderSceneMotion { cameraMotion: VideoCameraMotion; transition: VideoTransition; overlays: VideoMotionOverlay[]; map: VideoMotionMapChoreography | null; }
export interface VideoRenderSceneInput { id: string; manifestId: string; sceneIndex: number; compositionSceneId: string; plannedSceneId: string; startMs: number; endMs: number; durationMs: number; audioSegmentId: string; audioPath: string; assetStrategy: VideoCompositionAssetStrategy; selectedCandidateId: string | null; candidateIdentityHash: string | null; mediaAssetId: string | null; internalVisual: InternalVisualSpecification | null; mediaType: string | null; mimeType: string | null; storageProvider: string | null; storageKey: string | null; checksum: string | null; motion?: VideoRenderSceneMotion | null; }
export interface VideoRenderInputManifest extends VideoRenderInputIdentity { id: string; projectId: string; contentScriptId: string; version: string; inputHash: string; status: VideoRenderInputManifestStatus; audioOutputPath: string | null; totalDurationMs: number; sceneCount: number; failureCode: VideoRenderInputFailureCode | null; failureReason: string | null; createdAt: string; updatedAt: string; scenes: VideoRenderSceneInput[]; }
export interface VideoRenderManifestIdentity { renderInputManifestId: string; renderInputHash: string; }
export interface VideoRenderJobProgress { completedUnits: number; totalUnits: number; percent: number; }
export interface VideoRenderOutputArtifact { storageProvider: string; storageKey: string; mimeType: 'video/mp4' | 'video/webm' | 'video/quicktime'; checksum: string; sizeBytes: number; durationMs: number; }
export interface VideoRenderJob extends VideoRenderManifestIdentity { id: string; projectId: string; contentScriptId: string; attemptId: string; attemptNumber: number; status: VideoRenderJobStatus; progress: VideoRenderJobProgress | null; outputArtifact: VideoRenderOutputArtifact | null; failureCode: VideoRenderJobFailureCode | null; failureMessage: string | null; queuedAt: string; startedAt: string | null; completedAt: string | null; updatedAt: string; }
export interface VideoRenderWorkerIdentity extends VideoRenderManifestIdentity { jobId: string; attemptId: string; }
export interface VideoRenderProgressUpdate extends VideoRenderWorkerIdentity { completedUnits: number; totalUnits: number; }
export interface VideoRenderCompletionUpdate extends VideoRenderWorkerIdentity { completedUnits: number; totalUnits: number; outputArtifact: VideoRenderOutputArtifact; }
export interface VideoRenderFailureUpdate extends VideoRenderWorkerIdentity { message?: string; }
