import type { SceneVisualRequirementType, VisualAcquisitionStrategy, VisualAssetCandidateStatus, VisualAssetManifestStatus, VisualAssetAcquisitionRunStatus, VisualAssetProviderCapability } from './enums.js';

export interface VisualAssetManifest { id: string; projectId: string; contentScriptId: string; scenePlanId: string; scenePlanInputHash: string; manifestVersion: string; inputHash: string; status: VisualAssetManifestStatus; failureCode: string | null; failureReason: string | null; createdAt: string; updatedAt: string; completedAt: string | null; requirements: SceneVisualRequirement[]; }
export interface VisualAssetLicenceRequirements { commercialUseRequired: boolean; modificationAllowed: boolean; attributionRequired: boolean; provenanceRequired: boolean; unknownLicenceRequiresManualReview: boolean; }
export interface SceneVisualRequirement { id: string; manifestId: string; plannedSceneId: string; sceneIndex: number; requirementVersion: string; requirementType: SceneVisualRequirementType; acquisitionStrategy: VisualAcquisitionStrategy; subject: string | null; explicitEntities: string[]; explicitLocations: string[]; timeframe: string | null; eventOrClaim: string | null; visualObjective: string; visualDescription: string; mustInclude: string[]; mustAvoid: string[]; primarySearchQuery: string | null; alternateSearchQueries: string[]; generationPrompt: string | null; sourceFactIds: string[]; targetDurationMs: number; targetAspectRatio: string; preferredOrientation: string; expectedMediaType: string; licenceRequirements: VisualAssetLicenceRequirements; mapSpecification: Record<string, unknown> | null; programmaticSpecification: Record<string, unknown> | null; textCardSpecification: Record<string, unknown> | null; manualReviewRequired: boolean; reviewReasons: string[]; status: string; selectedCandidateId: string | null; candidateCount: number; createdAt: string; updatedAt: string; }
export interface VisualAssetCandidate { id: string; requirementId: string; provider: string; providerAssetId: string | null; sourceUrl: string | null; previewUrl: string | null; mediaIdentity: string | null; mediaType: string; mimeType: string | null; width: number | null; height: number | null; durationMs: number | null; checksum: string | null; title: string | null; licenceType: string | null; licenceUrl: string | null; attributionText: string | null; commercialUseAllowed: boolean | null; modificationAllowed: boolean | null; provenanceScore: number | null; overallScore: number | null; rejectionReasons: string[]; status: VisualAssetCandidateStatus; discoveredAt: string; selectedAt: string | null; approvedAt: string | null; }
export interface VisualAssetAcquisitionPlan { requirementId: string; plannedSceneId: string; requirementType: SceneVisualRequirementType; acquisitionStrategy: VisualAcquisitionStrategy; capability: VisualAssetProviderCapability | null; providerIds: string[]; queries: string[]; expectedMediaType: string; targetAspectRatio: string; preferredOrientation: string; licenceRequirements: VisualAssetLicenceRequirements; resultLimit: number; automaticAcquisitionAllowed: boolean; skipReason: string | null; manualReviewReasons: string[]; }
export interface VisualAssetAcquisitionProviderPlan { id: string; enabled: boolean; priority: number; capabilities: VisualAssetProviderCapability[]; strategies: VisualAcquisitionStrategy[]; resultLimit: number; version: string; configurationIdentity: string; }
export interface VisualAssetAcquisitionRun { id: string; projectId: string; contentScriptId: string; manifestId: string; manifestInputHash: string; version: string; inputHash: string; status: VisualAssetAcquisitionRunStatus; requestedRequirementIds: string[]; providerPlan: VisualAssetAcquisitionProviderPlan[]; preparedQueryCount: number; providerRequestCount: number; candidatesDiscovered: number; candidatesAccepted: number; candidatesRejected: number; failureCode: string | null; startedAt: string | null; completedAt: string | null; createdAt: string; updatedAt: string; plans: VisualAssetAcquisitionPlan[]; }
