import { Module } from '@nestjs/common';

import { storageProviders } from './storage.providers';
import {
  ContentRepository,
  ContentStyleProfileRepository,
  ProjectRepository,
  ProjectChannelRepository,
  ProjectEditorialProfileRepository,
  ResearchSourceRepository,
  SignalRepository,
  OpportunityRepository,
  OpportunityMetricRepository,
  EditorialAssessmentRepository,
  ResearchPackageRepository,
  TopicSelectionRepository,
  AiExecutionRepository,
  AiBatchRepository,
  ContentScriptRepository,
  TopicCandidateRepository,
  SemanticEmbeddingCacheRepository,
  ResearchExpansionRepository,
  ResearchAutomationRepository,
  ProductionQueueRepository,
  ScenePlanRepository,
  AudioGenerationRepository,
  VisualAssetRepository,
  VisualAssetAcquisitionRepository,
  VideoCompositionRepository,
  MediaAssetRepository,
  VideoRenderInputRepository,
  VideoRenderJobRepository,
  VideoMotionRepository,
  AgentRuntimeRepository,
  AgentPipelineRepository,
  GeographicReferenceRepository,
  SourceEvidenceContentRepository,
  SourceTranscriptRepository,
  TranscriptAcquisitionJobRepository,
} from '@content-os/storage';

@Module({
  providers: [...storageProviders],
  exports: [
    ContentRepository,
    ContentStyleProfileRepository,
    ProjectRepository,
    ProjectChannelRepository,
    ProjectEditorialProfileRepository,
    ResearchSourceRepository,
    SignalRepository,
    OpportunityRepository,
    OpportunityMetricRepository,
    EditorialAssessmentRepository,
    ResearchPackageRepository,
    TopicSelectionRepository,
    AiExecutionRepository,
    AiBatchRepository,
    ContentScriptRepository,
    TopicCandidateRepository,
    SemanticEmbeddingCacheRepository,
    ResearchExpansionRepository,
    ResearchAutomationRepository,
    ProductionQueueRepository,
    ScenePlanRepository,
    AudioGenerationRepository,
    VisualAssetRepository,
    VisualAssetAcquisitionRepository,
    VideoCompositionRepository,
    MediaAssetRepository,
    VideoRenderInputRepository,
    VideoRenderJobRepository,
    VideoMotionRepository,
    AgentRuntimeRepository,
    AgentPipelineRepository,
    GeographicReferenceRepository,
    SourceEvidenceContentRepository,
    SourceTranscriptRepository,
    TranscriptAcquisitionJobRepository,
  ],
})
export class StorageModule {}
