import { Injectable, NotFoundException, Optional } from "@nestjs/common";
import type { TopicSelection, TopicSelectionDecision, TopicSelectionEvaluationResult } from "@content-os/contracts";
import { OpportunityRepository, ProjectRepository, ResearchPackageRepository, TopicSelectionRepository, defaultProjectSelectionPolicy } from "@content-os/storage";
import { selectionScore } from "./topic-selection";
import { ResearchExecutionLogger } from './research-execution-logger.service';

@Injectable()
export class TopicSelectionService {
  constructor(private readonly opportunities: OpportunityRepository, private readonly packages: ResearchPackageRepository, private readonly selections: TopicSelectionRepository, private readonly projects: ProjectRepository, @Optional() private readonly executionLog?: ResearchExecutionLogger) {}
  async evaluate(projectId?: string, opportunityId?: string): Promise<TopicSelectionEvaluationResult> {
    if (projectId && !await this.projects.findById(projectId)) throw new NotFoundException("Project not found");
    const possibleRecords = opportunityId ? [await this.opportunities.findById(opportunityId)] : await this.opportunities.findAll(projectId);
    const records = possibleRecords.filter((record): record is NonNullable<typeof record> => record !== undefined);
    if (opportunityId && !records.length) throw new NotFoundException("Opportunity not found");
    this.executionLog?.event('debug', 'topic_selection.lookup.completed', 'completed', { result: { projectId: projectId ?? null, requestedOpportunityId: opportunityId ?? null, opportunitiesFound: records.length } });
    const evaluated = await Promise.all(records.map(async opportunity => { const policy = await this.selections.upsertPolicy(opportunity.projectId, (await this.selections.findPolicy(opportunity.projectId)) ?? defaultProjectSelectionPolicy); const researchPackage = await this.packages.findByOpportunityId(opportunity.id); const score = selectionScore(opportunity.score, researchPackage?.confidenceScore ?? 0, researchPackage?.sourceCount ?? 0, opportunity.lastSeenAt); let decision: TopicSelectionDecision = "selected" as TopicSelectionDecision; let reason = `Opportunity score ${opportunity.score} and research confidence ${researchPackage?.confidenceScore ?? 0} meet project thresholds.`; if (opportunity.status === "rejected" || opportunity.score < policy.minimumOpportunityScore) { decision = "rejected" as TopicSelectionDecision; reason = opportunity.status === "rejected" ? "Opportunity rejected manually." : `Opportunity score ${opportunity.score} below required ${policy.minimumOpportunityScore}.`; } else if (policy.requireResearchPackage && !researchPackage || researchPackage && researchPackage.status !== "ready") { decision = "hold" as TopicSelectionDecision; reason = "A ready research package is required."; } else if (researchPackage && researchPackage.confidenceScore < policy.minimumResearchConfidence) { decision = "hold" as TopicSelectionDecision; reason = `Research confidence ${researchPackage.confidenceScore} below required ${policy.minimumResearchConfidence}.`; } else if (researchPackage && researchPackage.sourceCount < policy.minimumIndependentSources && !(policy.allowSingleSourceBreakingStories && researchPackage.sourceCount === 1)) { decision = "hold" as TopicSelectionDecision; reason = `Only ${researchPackage.sourceCount} independent source(s); project requires ${policy.minimumIndependentSources}.`; } this.executionLog?.withContext({ projectId: opportunity.projectId, opportunityId: opportunity.id, researchPackageId: researchPackage?.id }, () => this.executionLog?.event('debug', 'topic_selection.decision.computed', decision, { result: { policy, opportunityScore: opportunity.score, researchConfidence: researchPackage?.confidenceScore ?? 0, sourceCount: researchPackage?.sourceCount ?? 0, lastSeenAt: opportunity.lastSeenAt, selectionScore: score, reason } })); return { opportunity, researchPackage, policy, score, decision, reason }; }));
    if (!opportunityId) { const grouped = new Map<string, typeof evaluated>(); for (const item of evaluated.filter(item => item.decision === "selected")) grouped.set(item.opportunity.projectId, [...(grouped.get(item.opportunity.projectId) ?? []), item]); for (const candidates of grouped.values()) { candidates.sort((a,b) => b.score-a.score || b.opportunity.score-a.opportunity.score || (b.researchPackage?.confidenceScore ?? 0)-(a.researchPackage?.confidenceScore ?? 0) || b.opportunity.lastSeenAt.localeCompare(a.opportunity.lastSeenAt) || a.opportunity.id.localeCompare(b.opportunity.id)); const cap = candidates[0]?.policy.maxSelectedPerRun ?? 0; for (const item of candidates.slice(cap)) { item.decision = "hold" as TopicSelectionDecision; item.reason = `Held because the per-run selection cap of ${cap} was reached.`; } } }
    const result: TopicSelectionEvaluationResult = { opportunitiesEvaluated: evaluated.length, selectedCount: 0, holdCount: 0, rejectedCount: 0, decisionsUpdated: 0, warnings: [] }; for (const item of evaluated) { const persisted = await this.selections.upsert({ projectId: item.opportunity.projectId, opportunityId: item.opportunity.id, researchPackageId: item.researchPackage?.id ?? null, decision: item.decision, selectionScore: item.score, reason: item.reason, evaluatedAt: new Date().toISOString() }); this.executionLog?.withContext({ projectId: item.opportunity.projectId, opportunityId: item.opportunity.id, researchPackageId: item.researchPackage?.id }, () => this.executionLog?.event('info', 'topic_selection.decision.persisted', item.decision, { result: { selectionId: persisted.id, selectionScore: item.score, reason: item.reason } })); result.decisionsUpdated++; if (item.decision === "selected") result.selectedCount++; else if (item.decision === "hold") result.holdCount++; else result.rejectedCount++; } this.executionLog?.event('info', 'topic_selection.evaluation.completed', 'completed', { result }); return result;
  }
  async findAll(projectId?: string): Promise<TopicSelection[]> { return (await this.selections.findAll(projectId)).map(item => this.toSelection(item)); }
  /** Reuses the persisted project selection policy for the research lifecycle gate. */
  async evaluateOne(opportunityId: string): Promise<TopicSelection> { await this.evaluate(undefined, opportunityId); const selection = await this.selections.findByOpportunityId(opportunityId); if (!selection) throw new NotFoundException('Topic selection not found'); return this.toSelection(selection); }
  async findOne(id:string): Promise<TopicSelection> { const item=await this.selections.findById(id); if(!item) throw new NotFoundException("Topic selection not found"); return this.toSelection(item); }
  private toSelection(item: Awaited<ReturnType<TopicSelectionRepository['findById']>> extends infer T ? Exclude<T, undefined> : never): TopicSelection { const researchPackage = item.researchPackageId && item.researchPackageConfidenceScore !== null && item.researchPackageSourceCount !== null && item.researchPackageStatus !== null ? { id: item.researchPackageId, confidenceScore: item.researchPackageConfidenceScore, sourceCount: item.researchPackageSourceCount, status: item.researchPackageStatus } : null; return { id:item.id, projectId:item.projectId, opportunityId:item.opportunityId, researchPackageId:item.researchPackageId, opportunityTitle:item.opportunityTitle, project:{ id:item.projectId, name:item.projectName }, opportunity:{ id:item.opportunityId, title:item.opportunityTitle, score:item.opportunityScore, representativeUrl:item.representativeUrl }, researchPackage, decision:item.decision as TopicSelectionDecision, selectionScore:item.selectionScore, reason:item.reason, evaluatedAt:item.evaluatedAt, createdAt:item.createdAt, updatedAt:item.updatedAt }; }
}
