jest.mock('@content-os/storage', () => ({ OpportunityRepository: class OpportunityRepository {}, ProjectRepository: class ProjectRepository {}, ResearchPackageRepository: class ResearchPackageRepository {}, TopicSelectionRepository: class TopicSelectionRepository {}, defaultProjectSelectionPolicy: { minimumOpportunityScore: 60, minimumResearchConfidence: 60, minimumIndependentSources: 2, maxSelectedPerRun: 1, requireResearchPackage: true, allowSingleSourceBreakingStories: false } }));
import { TopicSelectionService } from './topic-selection.service';
import { selectionScore } from './topic-selection';

const policy = { minimumOpportunityScore: 60, minimumResearchConfidence: 60, minimumIndependentSources: 2, maxSelectedPerRun: 1, requireResearchPackage: true, allowSingleSourceBreakingStories: false };
const opportunity = (id: string, score = 80, status = 'detected') => ({ id, projectId: 'project-1', title: id, score, status, lastSeenAt: '2026-01-02T00:00:00.000Z' });
const pkg = (id: string, confidence = 80, sourceCount = 2, status = 'ready') => ({ id: `package-${id}`, confidenceScore: confidence, sourceCount, status });

describe('TopicSelectionService', () => {
  const opportunities = { findAll: jest.fn(), findById: jest.fn() }; const packages = { findByOpportunityId: jest.fn() }; const selections = { findPolicy: jest.fn(), upsertPolicy: jest.fn(), upsert: jest.fn(), findAll: jest.fn(), findById: jest.fn() }; const projects = { findById: jest.fn() }; const service = new TopicSelectionService(opportunities as never, packages as never, selections as never, projects as never);
  beforeEach(() => { jest.resetAllMocks(); projects.findById.mockResolvedValue({ id: 'project-1' }); selections.findPolicy.mockResolvedValue(policy); selections.upsertPolicy.mockResolvedValue({ projectId: 'project-1', ...policy }); selections.upsert.mockResolvedValue({}); });
  it('selects strong, holds weak evidence, and rejects low or manual scores', async () => { const records = [opportunity('strong'), opportunity('low-confidence'), opportunity('low-score', 20), opportunity('manual', 90, 'rejected')]; opportunities.findAll.mockResolvedValue(records); packages.findByOpportunityId.mockImplementation(async (id: string) => id === 'low-confidence' ? pkg(id, 20) : pkg(id)); const result = await service.evaluate('project-1'); const saved = selections.upsert.mock.calls.map(call => call[0]); expect(saved.map(item => item.decision)).toEqual(['selected','hold','rejected','rejected']); expect(result).toMatchObject({ opportunitiesEvaluated: 4, selectedCount: 1, holdCount: 1, rejectedCount: 2 }); });
  it('holds insufficient sources unless the breaking-story policy permits one source', async () => { const breaking = { ...policy, allowSingleSourceBreakingStories: true }; opportunities.findAll.mockResolvedValue([opportunity('one')]); packages.findByOpportunityId.mockResolvedValue(pkg('one', 80, 1)); await service.evaluate('project-1'); expect(selections.upsert.mock.calls[0][0].decision).toBe('hold'); selections.findPolicy.mockResolvedValue(breaking); selections.upsertPolicy.mockResolvedValue({ projectId: 'project-1', ...breaking }); await service.evaluate('project-1'); expect(selections.upsert.mock.calls[1][0].decision).toBe('selected'); });
  it('applies the cap to ranked candidates and keeps scores bounded', async () => { opportunities.findAll.mockResolvedValue([opportunity('lower', 70), opportunity('higher', 90)]); packages.findByOpportunityId.mockImplementation(async (id: string) => pkg(id, id === 'higher' ? 90 : 70)); await service.evaluate('project-1'); const saved = selections.upsert.mock.calls.map(call => call[0]); expect(saved.find(item => item.opportunityId === 'higher').decision).toBe('selected'); expect(saved.find(item => item.opportunityId === 'lower').decision).toBe('hold'); expect(selectionScore(200, 200, 9, '2026-01-02')).toBeLessThanOrEqual(100); expect(selectionScore(-20, -20, 0, '2026-01-02')).toBeGreaterThanOrEqual(0); });
  it('holds missing or non-ready packages', async () => { opportunities.findAll.mockResolvedValue([opportunity('missing'), opportunity('pending')]); packages.findByOpportunityId.mockImplementation(async (id: string) => id === 'missing' ? undefined : pkg(id, 80, 2, 'pending')); await service.evaluate('project-1'); expect(selections.upsert.mock.calls.map(call => call[0].decision)).toEqual(['hold','hold']); });
  it('reevaluates through the same opportunity upsert without inflating counts', async () => { opportunities.findAll.mockResolvedValue([opportunity('stable')]); packages.findByOpportunityId.mockResolvedValue(pkg('stable')); const first = await service.evaluate('project-1'); const second = await service.evaluate('project-1'); expect(selections.upsert.mock.calls.map(call => call[0].opportunityId)).toEqual(['stable', 'stable']); expect(first.selectedCount).toBe(1); expect(second).toMatchObject({ opportunitiesEvaluated: 1, selectedCount: 1, decisionsUpdated: 1 }); });
  it('updates the same decision when a policy threshold changes', async () => { const stricter = { ...policy, minimumOpportunityScore: 90 }; opportunities.findAll.mockResolvedValue([opportunity('policy', 80)]); packages.findByOpportunityId.mockResolvedValue(pkg('policy', 80)); selections.findPolicy.mockResolvedValueOnce(policy).mockResolvedValueOnce(stricter); selections.upsertPolicy.mockResolvedValueOnce({ projectId: 'project-1', ...policy }).mockResolvedValueOnce({ projectId: 'project-1', ...stricter }); await service.evaluate('project-1'); await service.evaluate('project-1'); expect(selections.upsert.mock.calls.map(call => call[0].decision)).toEqual(['selected', 'rejected']); expect(selections.upsert.mock.calls[1][0].reason).toContain('below required 90'); });
  it('maps joined list and detail contexts, including a null research package', async () => { const base = { id: 'selection-1', projectId: 'project-1', opportunityId: 'opportunity-1', researchPackageId: 'package-1', opportunityTitle: 'Story', projectName: 'Project', opportunityScore: 80, representativeUrl: 'https://example.com/story', researchPackageConfidenceScore: 75, researchPackageSourceCount: 2, researchPackageStatus: 'ready', decision: 'selected', selectionScore: 78, reason: 'Meets thresholds.', evaluatedAt: '2026-01-01', createdAt: '2026-01-01', updatedAt: '2026-01-01' }; selections.findAll.mockResolvedValue([base, { ...base, id: 'selection-2', opportunityId: 'opportunity-2', researchPackageId: null, researchPackageConfidenceScore: null, researchPackageSourceCount: null, researchPackageStatus: null }]); selections.findById.mockResolvedValue(base); const list = await service.findAll(); const detail = await service.findOne(base.id); expect(list[0]).toMatchObject({ project: { id: 'project-1', name: 'Project' }, opportunity: { id: 'opportunity-1', title: 'Story', score: 80, representativeUrl: 'https://example.com/story' }, researchPackage: { id: 'package-1', confidenceScore: 75, sourceCount: 2, status: 'ready' } }); expect(list[1].researchPackage).toBeNull(); expect(detail).toMatchObject({ project: { name: 'Project' }, opportunity: { score: 80 }, researchPackage: { confidenceScore: 75 } }); });
});
