import { createHash } from 'node:crypto';
import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { AudioGenerationStatus, SceneMediaStrategy, ScenePlanStatus, VisualAssetCandidateStatus, VisualAssetManifestStatus, validateInternalVisualSpecification } from '@content-os/contracts';
import { AudioGenerationRepository, ContentScriptRepository, ScenePlanRepository, VisualAssetRepository } from '@content-os/storage';
import type { ResolvedGeographicReference } from '@content-os/contracts';
import { GeographicReferenceResolver } from './geographic-reference-resolver';

const VERSION = 'visual-asset-manifest-v1';
const normalize = (value: string) => value.replace(/\s+/g, ' ').trim();
const mapping: Record<string, [string, string]> = {
  [SceneMediaStrategy.STOCK_OR_SOURCE_FOOTAGE]: ['stock_footage', 'provider_search'], [SceneMediaStrategy.EXISTING_ASSET]: ['source_footage', 'source_reference'], [SceneMediaStrategy.REUSABLE_MAP_ANIMATION]: ['reusable_map_animation', 'reusable_template'], [SceneMediaStrategy.PROGRAMMATIC_ANIMATION]: ['programmatic_animation', 'programmatic_specification'], [SceneMediaStrategy.TEXT_ONLY]: ['text_card', 'none_required'], [SceneMediaStrategy.AI_IMAGE]: ['generated_image', 'generated'], [SceneMediaStrategy.AI_IMAGE_TO_VIDEO]: ['generated_video', 'generated'], [SceneMediaStrategy.GENERATED_VIDEO]: ['generated_video', 'generated'], [SceneMediaStrategy.PRESENTER]: ['presenter', 'manual'], [SceneMediaStrategy.SCREEN_CAPTURE]: ['screen_demo', 'manual'], [SceneMediaStrategy.MANUAL]: ['manual_asset', 'manual'], [SceneMediaStrategy.REUSABLE_ASSET]: ['still_image', 'reusable_template'],
};
const stableId = (kind: string, value: string) => `${kind}-${createHash('sha256').update(`${kind}:${normalize(value).toLowerCase()}`).digest('hex').slice(0, 12)}`;
const has = (value: string, expression: RegExp) => expression.test(value);
const labels = (scene: any) => typeof scene.onScreenText === 'string' && normalize(scene.onScreenText) ? [normalize(scene.onScreenText)] : [];
const viewport = (source: string) => ({ framing: has(source, /\b(zoom(?:ed)?|close[- ]?up|narrow)\b/i) ? 'close' as const : has(source, /\b(wider|regional|global|wide)\b/i) ? 'wide' as const : 'auto' as const, geometryStatus: 'unavailable' as const });
const namedRegions = (scene: any) => [...new Set<string>((Array.isArray(scene.explicitLocations) ? scene.explicitLocations : []).map((value: unknown) => typeof value === 'string' ? normalize(value) : '').filter((value: string): value is string => Boolean(value)))].sort().slice(0, 12).map((label, index) => ({ id: stableId('region', label), label, geometryStatus: 'named_region' as const, emphasis: index === 0 ? 'primary' as const : 'secondary' as const }));
const mapZones = (source: string) => {
  const rules: Array<[RegExp, 'chokepoint' | 'pressure' | 'blockade', string]> = [[/\bchokepoint\b|\bnarrow (?:channel|corridor)\b/i, 'chokepoint', 'Chokepoint'], [/\bpressure\b|\bdisruption\b/i, 'pressure', 'Pressure zone'], [/\bblockade\b/i, 'blockade', 'Blockade zone']];
  return rules.filter(([expression]) => has(source, expression)).map(([, kind, label], index) => ({ id: stableId('zone', `${kind}:${label}`), label, kind, geometryStatus: 'unavailable' as const, emphasis: index === 0 ? 'primary' as const : 'secondary' as const }));
};
/** Converts explicit Scene Plan visual intent into bounded execution primitives; it never infers coordinates. */
export const createInternalVisualSpecification = (requirementType: string, scene: any, geographicReferences: ResolvedGeographicReference[] = []) => {
  const label = typeof scene.onScreenText === 'string' && normalize(scene.onScreenText) ? normalize(scene.onScreenText) : null;
  const focus = typeof scene.primarySearchQuery === 'string' && normalize(scene.primarySearchQuery) ? normalize(scene.primarySearchQuery) : normalize(scene.visualDescription);
  const source = `${scene.primarySearchQuery ?? ''} ${scene.visualDescription ?? ''}`;
  const zones = mapZones(source);
  const value = requirementType === 'reusable_map_animation'
    ? { type: 'map', version: 'internal-visual-v1', spec: { focus, viewport: viewport(source), highlightedRegions: namedRegions(scene).map((region) => region.label), regionDetails: namedRegions(scene), geographicReferences, markers: geographicReferences.flatMap((reference) => reference.point ? [{ id: reference.id, latitude: reference.point.latitude, longitude: reference.point.longitude, label: reference.canonicalName, role: 'focus' as const, emphasis: 'primary' as const }] : []), routes: [], zones, labels: labels(scene), emphasisTargets: zones.map((zone) => zone.label) } }
    : requirementType === 'programmatic_animation'
      ? { type: 'flow_or_corridor', version: 'internal-visual-v1', spec: { direction: has(source, /\b(reverse|returning|backward)\b/i) ? 'reverse' as const : has(source, /\b(bidirectional|two-way|both directions)\b/i) ? 'bidirectional' as const : 'forward' as const, lanes: [], laneConfiguration: [{ id: stableId('lane', 'primary'), role: 'primary' as const, geometryStatus: 'unavailable' as const }], movingEntities: has(source, /\b(traffic|flow(?:ing)?|ships?|vehicles?|entities?)\b/i) ? ['generic'] : [], entityConfiguration: has(source, /\b(traffic|flow(?:ing)?|ships?|vehicles?|entities?)\b/i) ? [{ id: stableId('entity', 'generic'), kind: 'generic' as const, count: 3 }] : [], compression: has(source, /\bpressure\b|\bdisruption\b/i) ? 'pressure' as const : has(source, /\bslow(?:s|ed|ing)?\b|\bcompress(?:ion|ed)?\b/i) ? 'slowdown' as const : 'none' as const, progression: has(source, /\bapproach(?:es|ing)?\b|\bwave\b/i) ? 'approach' as const : has(source, /\bpulse\b/i) ? 'pulse' as const : 'steady' as const, pressureZone: zones[0]?.label ?? null, pressureZoneDetails: zones[0] ? { id: stableId('pressure', zones[0].kind), label: zones[0].label, kind: zones[0].kind === 'blockade' ? 'blockade' as const : zones[0].kind === 'chokepoint' ? 'chokepoint' as const : 'pressure' as const } : null, labels: labels(scene), emphasisTargets: zones.map((zone) => zone.label) } }
      : requirementType === 'text_card' ? { type: 'text_card', version: 'internal-visual-v1', spec: { primaryText: label ?? normalize(scene.visualDescription), secondaryText: null, emphasis: 'primary', layout: 'centered' } }
        : requirementType === 'chart_or_infographic' ? { type: 'chart_or_screenshot', version: 'internal-visual-v1', spec: { intent: normalize(scene.visualDescription), labels: label ? [label] : [], dataReferences: Array.isArray(scene.citedFactIds) ? scene.citedFactIds : [] } }
          : null;
  return value ? validateInternalVisualSpecification(value) : null;
};

@Injectable()
export class VisualAssetRuntimeService {
  private readonly inFlight = new Set<string>();
  constructor(private readonly scripts: ContentScriptRepository, private readonly plans: ScenePlanRepository, private readonly audio: AudioGenerationRepository, private readonly manifests: VisualAssetRepository, private readonly geography?: GeographicReferenceResolver) {}
  async prepare(contentScriptId: string) {
    if (this.inFlight.has(contentScriptId)) throw new ConflictException('Visual asset manifest preparation is already in progress'); this.inFlight.add(contentScriptId);
    try {
      const script = await this.scripts.findById(contentScriptId); if (!script) throw new NotFoundException('Content Script not found'); if (script.status !== 'ready') throw new ConflictException('Content Script is not ready');
      const plan = await this.plans.findByContentScriptId(contentScriptId); if (!plan || plan.projectId !== script.projectId) throw new NotFoundException('Scene Plan not found'); if (plan.status !== ScenePlanStatus.READY || !plan.scenes.length) throw new ConflictException('Ready Scene Plan is required'); if (normalize(plan.scenes.map((scene: any) => scene.narration).join(' ')) !== normalize(script.fullScript)) throw new ConflictException('Scene Plan narration does not reconcile with Content Script');
      const audio = await this.audio.findByContentScriptId(contentScriptId); const durations = new Map(audio?.status === AudioGenerationStatus.READY && audio.scenePlanId === plan.id ? audio.segments.map((segment: any) => [segment.sceneId, segment.actualDurationMs] as const) : []);
      const requirements = await Promise.all(plan.scenes.map(async (scene: any) => {
        const [requirementType, acquisitionStrategy] = mapping[scene.mediaStrategy] ?? ['manual_asset', 'manual']; const entities = (Array.isArray(script.geographicEntities) ? script.geographicEntities : []).filter((entity: any) => Array.isArray(scene.geographicEntityIds) && scene.geographicEntityIds.includes(entity.id)); const explicitLocations = entities.map((entity: any) => entity.canonicalName); const geographicReferences = requirementType === 'reusable_map_animation' && this.geography ? await this.geography.resolve(explicitLocations) : []; const specification = createInternalVisualSpecification(requirementType, { ...scene, explicitLocations }, geographicReferences); const isInternal = ['none_required', 'reusable_template', 'programmatic_specification'].includes(acquisitionStrategy); const ambiguityRequiresReview = /\b(it|this|that|they|them|there)\b/i.test(scene.visualDescription) && !scene.primarySearchQuery && !isInternal; const manualReviewRequired = scene.manualReview || ambiguityRequiresReview || acquisitionStrategy === 'manual'; const reviewReasons = [...(scene.manualReviewReason ? [scene.manualReviewReason] : []), ...(ambiguityRequiresReview ? ['ambiguous_visual_subject'] : []), ...(acquisitionStrategy === 'manual' ? ['unsupported_acquisition_strategy'] : [])];
        return { id: createHash('sha256').update(`${plan.id}:${scene.id}:${VERSION}`).digest('hex'), plannedSceneId: scene.id, requirementVersion: VERSION, requirementType, acquisitionStrategy, subject: scene.primarySearchQuery ?? null, explicitEntities: [], explicitLocations, geographicReferenceIds: geographicReferences.map((reference) => reference.id), timeframe: null, eventOrClaim: null, visualObjective: scene.visualDescription, visualDescription: scene.visualDescription, mustInclude: [], mustAvoid: [], primarySearchQuery: scene.primarySearchQuery, alternateSearchQueries: scene.alternateSearchQueries, generationPrompt: scene.generatedMediaPrompt, sourceFactIds: scene.citedFactIds, targetDurationMs: durations.get(scene.id) ?? scene.estimatedDurationMs, targetAspectRatio: '9:16', preferredOrientation: 'portrait', expectedMediaType: requirementType.includes('footage') || requirementType.includes('video') ? 'video' : 'image', licenceRequirements: { commercialUseRequired: true, modificationAllowed: true, attributionRequired: false, provenanceRequired: true, unknownLicenceRequiresManualReview: true }, mapSpecification: specification?.type === 'map' ? { version: 'map-spec-v1', focus: specification.spec.focus, viewport: specification.spec.viewport, zoneIds: specification.spec.zones.map((zone) => zone.id) } : null, programmaticSpecification: specification?.type === 'flow_or_corridor' ? { version: 'programmatic-spec-v1', laneIds: specification.spec.laneConfiguration.map((lane) => lane.id), progression: specification.spec.progression } : requirementType === 'chart_or_infographic' ? { version: 'programmatic-spec-v1' } : null, textCardSpecification: requirementType === 'text_card' ? { version: 'text-card-spec-v1', headline: scene.onScreenText ?? null } : null, internalVisual: specification, manualReviewRequired, reviewReasons, status: manualReviewRequired ? 'needs_review' : 'ready', selectedCandidateId: null };
      }));
      const inputHash = createHash('sha256').update(JSON.stringify({ VERSION, scriptId: script.id, scriptInputHash: script.inputHash, planId: plan.id, planHash: plan.inputHash, audio: audio?.status === AudioGenerationStatus.READY ? { id: audio.id, inputHash: audio.inputHash, durations: [...durations] } : null, requirements })).digest('hex'); const current = await this.manifests.findByContentScriptId(contentScriptId); if (current?.status === VisualAssetManifestStatus.READY && current.inputHash === inputHash) return current; const unresolved = requirements.some((requirement) => requirement.manualReviewRequired || !['none_required', 'reusable_template', 'programmatic_specification'].includes(requirement.acquisitionStrategy)); return this.manifests.upsert({ projectId: script.projectId, contentScriptId: script.id, scenePlanId: plan.id, scenePlanInputHash: plan.inputHash, manifestVersion: VERSION, inputHash, status: unresolved ? VisualAssetManifestStatus.NEEDS_REVIEW : VisualAssetManifestStatus.READY, failureCode: null, failureReason: null, completedAt: unresolved ? null : new Date().toISOString() }, requirements);
    } finally { this.inFlight.delete(contentScriptId); }
  }
  async find(contentScriptId: string) { const manifest = await this.manifests.findByContentScriptId(contentScriptId); if (!manifest) throw new NotFoundException('Visual asset manifest not found'); return manifest; }
  private async mutableRequirement(contentScriptId: string, requirementId: string) { const manifest = await this.find(contentScriptId); if (manifest.status === VisualAssetManifestStatus.STALE) throw new ConflictException('Stale visual asset manifest cannot be changed'); const requirement = manifest.requirements.find((item: any) => item.id === requirementId); if (!requirement) throw new NotFoundException('Visual requirement not found'); return { manifest, requirement }; }
  async listCandidates(contentScriptId: string, requirementId: string) { const { requirement } = await this.mutableRequirement(contentScriptId, requirementId); return this.manifests.listCandidates(requirement.id); }
  async upsertCandidate(contentScriptId: string, requirementId: string, data: any) { const { manifest, requirement } = await this.mutableRequirement(contentScriptId, requirementId); if (!data.provider || (!data.providerAssetId && !data.sourceUrl)) throw new ConflictException('Candidate provenance is required'); const candidate = await this.manifests.upsertCandidate(requirement.id, { ...data, status: data.status ?? VisualAssetCandidateStatus.DISCOVERED, rejectionReasons: data.rejectionReasons ?? [] }); await this.manifests.recalculateManifestStatus(manifest.id); return candidate; }
  async selectCandidate(contentScriptId: string, requirementId: string, candidateId: string) { const { manifest, requirement } = await this.mutableRequirement(contentScriptId, requirementId); const candidate = (await this.manifests.listCandidates(requirement.id)).find((item: any) => item.id === candidateId); if (!candidate) throw new NotFoundException('Visual candidate not found'); if (candidate.status === VisualAssetCandidateStatus.REJECTED) throw new ConflictException('Rejected candidate cannot be selected'); if (!candidate.sourceUrl && !candidate.providerAssetId) throw new ConflictException('Candidate provenance is required'); if (requirement.licenceRequirements.commercialUseRequired && candidate.commercialUseAllowed !== true) throw new ConflictException('Candidate commercial-use licence is required'); if (requirement.licenceRequirements.modificationAllowed && candidate.modificationAllowed !== true) throw new ConflictException('Candidate modification permission is required'); if (requirement.licenceRequirements.attributionRequired && !candidate.attributionText) throw new ConflictException('Candidate attribution is required'); if (candidate.mediaType !== requirement.expectedMediaType) throw new ConflictException('Candidate media metadata is incompatible'); await this.manifests.select(requirement.id, candidateId); await this.manifests.recalculateManifestStatus(manifest.id); return this.find(contentScriptId); }
  async rejectCandidate(contentScriptId: string, requirementId: string, candidateId: string, reason: string) { const { manifest, requirement } = await this.mutableRequirement(contentScriptId, requirementId); if (!normalize(reason) || normalize(reason).length > 200) throw new ConflictException('Candidate rejection reason is invalid'); const candidate = (await this.manifests.listCandidates(requirement.id)).find((item: any) => item.id === candidateId); if (!candidate) throw new NotFoundException('Visual candidate not found'); await this.manifests.reject(requirement.id, candidateId, [normalize(reason)]); await this.manifests.recalculateManifestStatus(manifest.id); return this.find(contentScriptId); }
  async clearCandidateSelection(contentScriptId: string, requirementId: string) { const { manifest, requirement } = await this.mutableRequirement(contentScriptId, requirementId); await this.manifests.clear(requirement.id); await this.manifests.recalculateManifestStatus(manifest.id); return this.find(contentScriptId); }
  async finalize(contentScriptId: string) { const manifest = await this.find(contentScriptId); if (manifest.status === VisualAssetManifestStatus.STALE) throw new ConflictException('Stale visual asset manifest cannot be finalized'); await this.manifests.recalculateManifestStatus(manifest.id); return this.find(contentScriptId); }
}
